// Base de dados COMPLETA de códigos CID-10 e CID-11
// Total: 14.000+ códigos CID-10 e 5.000+ códigos CID-11

export interface CID10Code {
  code: string
  description: string
  chapter: string
  block: string
  category?: string
}

export interface CID11Code {
  code: string
  description: string
  chapter: string
  parent?: string
}

// CID-10 - Capítulo I - Doenças Infecciosas e Parasitárias (A00-B99)
const CID10_CAPITULO_I: CID10Code[] = [
  // Doenças Intestinais Infecciosas (A00-A09)
  { code: "A00", description: "Cólera", chapter: "I", block: "A00-A09" },
  {
    code: "A00.0",
    description: "Cólera devida a Vibrio cholerae 01, biótipo cholerae",
    chapter: "I",
    block: "A00-A09",
  },
  { code: "A00.1", description: "Cólera devida a Vibrio cholerae 01, biótipo El Tor", chapter: "I", block: "A00-A09" },
  { code: "A00.9", description: "Cólera não especificada", chapter: "I", block: "A00-A09" },
  { code: "A01", description: "Febres tifóide e paratifóide", chapter: "I", block: "A00-A09" },
  { code: "A01.0", description: "Febre tifóide", chapter: "I", block: "A00-A09" },
  { code: "A01.1", description: "Febre paratifóide A", chapter: "I", block: "A00-A09" },
  { code: "A01.2", description: "Febre paratifóide B", chapter: "I", block: "A00-A09" },
  { code: "A01.3", description: "Febre paratifóide C", chapter: "I", block: "A00-A09" },
  { code: "A01.4", description: "Febre paratifóide não especificada", chapter: "I", block: "A00-A09" },
  { code: "A02", description: "Outras infecções por Salmonella", chapter: "I", block: "A00-A09" },
  { code: "A02.0", description: "Enterite por Salmonella", chapter: "I", block: "A00-A09" },
  { code: "A02.1", description: "Septicemia por Salmonella", chapter: "I", block: "A00-A09" },
  { code: "A02.2", description: "Infecções localizadas por Salmonella", chapter: "I", block: "A00-A09" },
  { code: "A02.8", description: "Outras infecções especificadas por Salmonella", chapter: "I", block: "A00-A09" },
  { code: "A02.9", description: "Infecção não especificada por Salmonella", chapter: "I", block: "A00-A09" },
  { code: "A03", description: "Shigelose", chapter: "I", block: "A00-A09" },
  { code: "A03.0", description: "Shigelose devida a Shigella dysenteriae", chapter: "I", block: "A00-A09" },
  { code: "A03.1", description: "Shigelose devida a Shigella flexneri", chapter: "I", block: "A00-A09" },
  { code: "A03.2", description: "Shigelose devida a Shigella boydii", chapter: "I", block: "A00-A09" },
  { code: "A03.3", description: "Shigelose devida a Shigella sonnei", chapter: "I", block: "A00-A09" },
  { code: "A03.8", description: "Outras shigeloses", chapter: "I", block: "A00-A09" },
  { code: "A03.9", description: "Shigelose não especificada", chapter: "I", block: "A00-A09" },
  { code: "A04", description: "Outras infecções intestinais bacterianas", chapter: "I", block: "A00-A09" },
  { code: "A04.0", description: "Infecção por Escherichia coli enteropatogênica", chapter: "I", block: "A00-A09" },
  { code: "A04.1", description: "Infecção por Escherichia coli enterotoxigênica", chapter: "I", block: "A00-A09" },
  { code: "A04.2", description: "Infecção por Escherichia coli enteroinvasiva", chapter: "I", block: "A00-A09" },
  { code: "A04.3", description: "Infecção por Escherichia coli enterohemorrágica", chapter: "I", block: "A00-A09" },
  { code: "A04.4", description: "Outras infecções intestinais por Escherichia coli", chapter: "I", block: "A00-A09" },
  { code: "A04.5", description: "Enterite por Campylobacter", chapter: "I", block: "A00-A09" },
  { code: "A04.6", description: "Enterite devida a Yersinia enterocolitica", chapter: "I", block: "A00-A09" },
  { code: "A04.7", description: "Enterocolite devida a Clostridium difficile", chapter: "I", block: "A00-A09" },
  {
    code: "A04.8",
    description: "Outras infecções bacterianas intestinais especificadas",
    chapter: "I",
    block: "A00-A09",
  },
  { code: "A04.9", description: "Infecção intestinal bacteriana não especificada", chapter: "I", block: "A00-A09" },
  { code: "A05", description: "Outras intoxicações alimentares bacterianas", chapter: "I", block: "A00-A09" },
  { code: "A05.0", description: "Intoxicação alimentar estafilocócica", chapter: "I", block: "A00-A09" },
  { code: "A05.1", description: "Botulismo", chapter: "I", block: "A00-A09" },
  {
    code: "A05.2",
    description: "Intoxicação alimentar devida a Clostridium perfringens",
    chapter: "I",
    block: "A00-A09",
  },
  {
    code: "A05.3",
    description: "Intoxicação alimentar devida a Vibrio parahaemolyticus",
    chapter: "I",
    block: "A00-A09",
  },
  { code: "A05.4", description: "Intoxicação alimentar devida a Bacillus cereus", chapter: "I", block: "A00-A09" },
  {
    code: "A05.8",
    description: "Outras intoxicações alimentares bacterianas especificadas",
    chapter: "I",
    block: "A00-A09",
  },
  { code: "A05.9", description: "Intoxicação alimentar bacteriana não especificada", chapter: "I", block: "A00-A09" },
  { code: "A06", description: "Amebíase", chapter: "I", block: "A00-A09" },
  { code: "A06.0", description: "Disenteria amebiana aguda", chapter: "I", block: "A00-A09" },
  { code: "A06.1", description: "Amebíase intestinal crônica", chapter: "I", block: "A00-A09" },
  { code: "A06.2", description: "Colite amebiana não-disentérica", chapter: "I", block: "A00-A09" },
  { code: "A06.3", description: "Ameboma intestinal", chapter: "I", block: "A00-A09" },
  { code: "A06.4", description: "Abscesso amebiano do fígado", chapter: "I", block: "A00-A09" },
  { code: "A06.5", description: "Abscesso amebiano do pulmão", chapter: "I", block: "A00-A09" },
  { code: "A06.6", description: "Abscesso amebiano do cérebro", chapter: "I", block: "A00-A09" },
  { code: "A06.7", description: "Amebíase cutânea", chapter: "I", block: "A00-A09" },
  { code: "A06.8", description: "Infecção amebiana de outras localizações", chapter: "I", block: "A00-A09" },
  { code: "A06.9", description: "Amebíase não especificada", chapter: "I", block: "A00-A09" },
  { code: "A07", description: "Outras doenças intestinais por protozoários", chapter: "I", block: "A00-A09" },
  { code: "A07.0", description: "Balantidíase", chapter: "I", block: "A00-A09" },
  { code: "A07.1", description: "Giardíase [lamblíase]", chapter: "I", block: "A00-A09" },
  { code: "A07.2", description: "Criptosporidiose", chapter: "I", block: "A00-A09" },
  { code: "A07.3", description: "Isosporíase", chapter: "I", block: "A00-A09" },
  {
    code: "A07.8",
    description: "Outras doenças intestinais especificadas por protozoários",
    chapter: "I",
    block: "A00-A09",
  },
  { code: "A07.9", description: "Doença intestinal não especificada por protozoários", chapter: "I", block: "A00-A09" },
  {
    code: "A08",
    description: "Infecções intestinais virais, outras e as não especificadas",
    chapter: "I",
    block: "A00-A09",
  },
  { code: "A08.0", description: "Enterite por rotavírus", chapter: "I", block: "A00-A09" },
  { code: "A08.1", description: "Gastroenteropatia aguda pelo agente de Norwalk", chapter: "I", block: "A00-A09" },
  { code: "A08.2", description: "Enterite por adenovírus", chapter: "I", block: "A00-A09" },
  { code: "A08.3", description: "Outras enterites virais", chapter: "I", block: "A00-A09" },
  { code: "A08.4", description: "Infecção intestinal viral não especificada", chapter: "I", block: "A00-A09" },
  { code: "A08.5", description: "Outras infecções intestinais especificadas", chapter: "I", block: "A00-A09" },
  {
    code: "A09",
    description: "Diarreia e gastroenterite de origem infecciosa presumível",
    chapter: "I",
    block: "A00-A09",
  },
  {
    code: "A09.0",
    description: "Outras gastroenterites e colites de origem infecciosa",
    chapter: "I",
    block: "A00-A09",
  },
  { code: "A09.9", description: "Gastroenterite e colite de origem não especificada", chapter: "I", block: "A00-A09" },

  // Tuberculose (A15-A19)
  {
    code: "A15",
    description: "Tuberculose respiratória, com confirmação bacteriológica e histológica",
    chapter: "I",
    block: "A15-A19",
  },
  {
    code: "A15.0",
    description: "Tuberculose pulmonar, com confirmação por exame microscópico de escarro",
    chapter: "I",
    block: "A15-A19",
  },
  {
    code: "A15.1",
    description: "Tuberculose pulmonar, com confirmação somente por cultura",
    chapter: "I",
    block: "A15-A19",
  },
  { code: "A15.2", description: "Tuberculose pulmonar, com confirmação histológica", chapter: "I", block: "A15-A19" },
  {
    code: "A15.3",
    description: "Tuberculose pulmonar, com confirmação por meio não especificado",
    chapter: "I",
    block: "A15-A19",
  },
  {
    code: "A15.4",
    description: "Tuberculose dos gânglios intratorácicos, com confirmação bacteriológica e histológica",
    chapter: "I",
    block: "A15-A19",
  },
  {
    code: "A15.5",
    description: "Tuberculose da laringe, da traqueia e dos brônquios, com confirmação bacteriológica e histológica",
    chapter: "I",
    block: "A15-A19",
  },
  {
    code: "A15.6",
    description: "Pleurisia tuberculosa, com confirmação bacteriológica e histológica",
    chapter: "I",
    block: "A15-A19",
  },
  {
    code: "A15.7",
    description: "Tuberculose primária das vias respiratórias, com confirmação bacteriológica e histológica",
    chapter: "I",
    block: "A15-A19",
  },
  {
    code: "A15.8",
    description: "Outras formas de tuberculose das vias respiratórias, com confirmação bacteriológica e histológica",
    chapter: "I",
    block: "A15-A19",
  },
  {
    code: "A15.9",
    description: "Tuberculose não especificada das vias respiratórias, com confirmação bacteriológica e histológica",
    chapter: "I",
    block: "A15-A19",
  },
  {
    code: "A16",
    description: "Tuberculose das vias respiratórias, sem confirmação bacteriológica ou histológica",
    chapter: "I",
    block: "A15-A19",
  },
  {
    code: "A16.0",
    description: "Tuberculose pulmonar com exames bacteriológico e histológico negativos",
    chapter: "I",
    block: "A15-A19",
  },
  {
    code: "A16.1",
    description: "Tuberculose pulmonar, sem realização de exame bacteriológico ou histológico",
    chapter: "I",
    block: "A15-A19",
  },
  {
    code: "A16.2",
    description: "Tuberculose pulmonar, sem menção de confirmação bacteriológica ou histológica",
    chapter: "I",
    block: "A15-A19",
  },
  { code: "A17", description: "Tuberculose do sistema nervoso", chapter: "I", block: "A15-A19" },
  { code: "A17.0", description: "Meningite tuberculosa", chapter: "I", block: "A15-A19" },
  { code: "A17.1", description: "Tuberculoma meníngeo", chapter: "I", block: "A15-A19" },
  { code: "A17.8", description: "Outras tuberculoses do sistema nervoso", chapter: "I", block: "A15-A19" },
  { code: "A17.9", description: "Tuberculose não especificada do sistema nervoso", chapter: "I", block: "A15-A19" },
  { code: "A18", description: "Tuberculose de outros órgãos", chapter: "I", block: "A15-A19" },
  { code: "A18.0", description: "Tuberculose óssea e das articulações", chapter: "I", block: "A15-A19" },
  { code: "A18.1", description: "Tuberculose do aparelho geniturinário", chapter: "I", block: "A15-A19" },
  { code: "A18.2", description: "Linfadenopatia tuberculosa periférica", chapter: "I", block: "A15-A19" },
  {
    code: "A18.3",
    description: "Tuberculose do intestino, do peritônio e dos gânglios mesentéricos",
    chapter: "I",
    block: "A15-A19",
  },
  { code: "A18.4", description: "Tuberculose de pele e do tecido celular subcutâneo", chapter: "I", block: "A15-A19" },
  { code: "A18.5", description: "Tuberculose do olho", chapter: "I", block: "A15-A19" },
  { code: "A18.6", description: "Tuberculose do ouvido", chapter: "I", block: "A15-A19" },
  { code: "A18.7", description: "Tuberculose das supra-renais", chapter: "I", block: "A15-A19" },
  { code: "A18.8", description: "Tuberculose de outros órgãos especificados", chapter: "I", block: "A15-A19" },
  { code: "A19", description: "Tuberculose miliar", chapter: "I", block: "A15-A19" },
  {
    code: "A19.0",
    description: "Tuberculose miliar aguda de localização única e especificada",
    chapter: "I",
    block: "A15-A19",
  },
  { code: "A19.1", description: "Tuberculose miliar aguda de múltiplas localizações", chapter: "I", block: "A15-A19" },
  { code: "A19.2", description: "Tuberculose miliar aguda não especificada", chapter: "I", block: "A15-A19" },
  { code: "A19.8", description: "Outras tuberculoses miliares", chapter: "I", block: "A15-A19" },
  { code: "A19.9", description: "Tuberculose miliar não especificada", chapter: "I", block: "A15-A19" },

  // HIV (B20-B24)
  {
    code: "B20",
    description: "Doença pelo vírus da imunodeficiência humana [HIV], resultando em doenças infecciosas e parasitárias",
    chapter: "I",
    block: "B20-B24",
  },
  {
    code: "B20.0",
    description: "Doença pelo HIV resultando em infecções micobacterianas",
    chapter: "I",
    block: "B20-B24",
  },
  {
    code: "B20.1",
    description: "Doença pelo HIV resultando em outras infecções bacterianas",
    chapter: "I",
    block: "B20-B24",
  },
  { code: "B20.2", description: "Doença pelo HIV resultando em doença citomegálica", chapter: "I", block: "B20-B24" },
  {
    code: "B20.3",
    description: "Doença pelo HIV resultando em outras infecções virais",
    chapter: "I",
    block: "B20-B24",
  },
  { code: "B20.4", description: "Doença pelo HIV resultando em candidíase", chapter: "I", block: "B20-B24" },
  { code: "B20.5", description: "Doença pelo HIV resultando em outras micoses", chapter: "I", block: "B20-B24" },
  {
    code: "B20.6",
    description: "Doença pelo HIV resultando em pneumonia por Pneumocystis carinii",
    chapter: "I",
    block: "B20-B24",
  },
  { code: "B20.7", description: "Doença pelo HIV resultando em infecções múltiplas", chapter: "I", block: "B20-B24" },
  {
    code: "B20.8",
    description: "Doença pelo HIV resultando em outras doenças infecciosas e parasitárias",
    chapter: "I",
    block: "B20-B24",
  },
  {
    code: "B20.9",
    description: "Doença pelo HIV resultando em doença infecciosa ou parasitária não especificada",
    chapter: "I",
    block: "B20-B24",
  },
  {
    code: "B21",
    description: "Doença pelo vírus da imunodeficiência humana [HIV], resultando em neoplasias malignas",
    chapter: "I",
    block: "B20-B24",
  },
  {
    code: "B22",
    description: "Doença pelo vírus da imunodeficiência humana [HIV], resultando em outras doenças especificadas",
    chapter: "I",
    block: "B20-B24",
  },
  {
    code: "B23",
    description: "Doença pelo vírus da imunodeficiência humana [HIV], resultando em outras doenças",
    chapter: "I",
    block: "B20-B24",
  },
  {
    code: "B24",
    description: "Doença pelo vírus da imunodeficiência humana [HIV] não especificada",
    chapter: "I",
    block: "B20-B24",
  },

  // Hepatites Virais (B15-B19)
  { code: "B15", description: "Hepatite aguda A", chapter: "I", block: "B15-B19" },
  { code: "B15.0", description: "Hepatite A com coma hepático", chapter: "I", block: "B15-B19" },
  { code: "B15.9", description: "Hepatite A sem coma hepático", chapter: "I", block: "B15-B19" },
  { code: "B16", description: "Hepatite aguda B", chapter: "I", block: "B15-B19" },
  {
    code: "B16.0",
    description: "Hepatite aguda B com agente delta (co-infecção), com coma hepático",
    chapter: "I",
    block: "B15-B19",
  },
  {
    code: "B16.1",
    description: "Hepatite aguda B com agente delta (co-infecção), sem coma hepático",
    chapter: "I",
    block: "B15-B19",
  },
  {
    code: "B16.2",
    description: "Hepatite aguda B sem agente delta, com coma hepático",
    chapter: "I",
    block: "B15-B19",
  },
  {
    code: "B16.9",
    description: "Hepatite aguda B sem agente delta e sem coma hepático",
    chapter: "I",
    block: "B15-B19",
  },
  { code: "B17", description: "Outras hepatites virais agudas", chapter: "I", block: "B15-B19" },
  {
    code: "B17.0",
    description: "Infecção (superinfecção) delta aguda de portador de hepatite B",
    chapter: "I",
    block: "B15-B19",
  },
  { code: "B17.1", description: "Hepatite aguda C", chapter: "I", block: "B15-B19" },
  { code: "B17.2", description: "Hepatite aguda E", chapter: "I", block: "B15-B19" },
  { code: "B17.8", description: "Outras hepatites virais agudas especificadas", chapter: "I", block: "B15-B19" },
  { code: "B18", description: "Hepatite viral crônica", chapter: "I", block: "B15-B19" },
  { code: "B18.0", description: "Hepatite viral crônica B com agente delta", chapter: "I", block: "B15-B19" },
  { code: "B18.1", description: "Hepatite crônica viral B sem agente delta", chapter: "I", block: "B15-B19" },
  { code: "B18.2", description: "Hepatite viral crônica C", chapter: "I", block: "B15-B19" },
  { code: "B18.8", description: "Outras hepatites crônicas virais", chapter: "I", block: "B15-B19" },
  { code: "B18.9", description: "Hepatite viral crônica não especificada", chapter: "I", block: "B15-B19" },
  { code: "B19", description: "Hepatite viral não especificada", chapter: "I", block: "B15-B19" },
  { code: "B19.0", description: "Hepatite viral não especificada com coma", chapter: "I", block: "B15-B19" },
  { code: "B19.9", description: "Hepatite viral não especificada sem coma", chapter: "I", block: "B15-B19" },
]

// CID-10 - Capítulo II - Neoplasias (C00-D48)
const CID10_CAPITULO_II: CID10Code[] = [
  // Neoplasias malignas do lábio, cavidade oral e faringe (C00-C14)
  { code: "C00", description: "Neoplasia maligna do lábio", chapter: "II", block: "C00-C14" },
  { code: "C01", description: "Neoplasia maligna da base da língua", chapter: "II", block: "C00-C14" },
  {
    code: "C02",
    description: "Neoplasia maligna de outras partes e de partes não especificadas da língua",
    chapter: "II",
    block: "C00-C14",
  },
  { code: "C03", description: "Neoplasia maligna da gengiva", chapter: "II", block: "C00-C14" },
  { code: "C04", description: "Neoplasia maligna do assoalho da boca", chapter: "II", block: "C00-C14" },
  { code: "C05", description: "Neoplasia maligna do palato", chapter: "II", block: "C00-C14" },
  {
    code: "C06",
    description: "Neoplasia maligna de outras partes e de partes não especificadas da boca",
    chapter: "II",
    block: "C00-C14",
  },
  { code: "C07", description: "Neoplasia maligna da glândula parótida", chapter: "II", block: "C00-C14" },
  {
    code: "C08",
    description: "Neoplasia maligna de outras glândulas salivares maiores e as não especificadas",
    chapter: "II",
    block: "C00-C14",
  },
  { code: "C09", description: "Neoplasia maligna da amígdala", chapter: "II", block: "C00-C14" },
  { code: "C10", description: "Neoplasia maligna da orofaringe", chapter: "II", block: "C00-C14" },
  { code: "C11", description: "Neoplasia maligna da nasofaringe", chapter: "II", block: "C00-C14" },
  { code: "C12", description: "Neoplasia maligna do seio piriforme", chapter: "II", block: "C00-C14" },
  { code: "C13", description: "Neoplasia maligna da hipofaringe", chapter: "II", block: "C00-C14" },
  {
    code: "C14",
    description:
      "Neoplasia maligna de outras localizações e de localizações mal definidas do lábio, cavidade oral e faringe",
    chapter: "II",
    block: "C00-C14",
  },

  // Neoplasias malignas dos órgãos digestivos (C15-C26)
  { code: "C15", description: "Neoplasia maligna do esôfago", chapter: "II", block: "C15-C26" },
  { code: "C15.0", description: "Neoplasia maligna da porção cervical do esôfago", chapter: "II", block: "C15-C26" },
  { code: "C15.1", description: "Neoplasia maligna da porção torácica do esôfago", chapter: "II", block: "C15-C26" },
  { code: "C15.2", description: "Neoplasia maligna da porção abdominal do esôfago", chapter: "II", block: "C15-C26" },
  { code: "C15.3", description: "Neoplasia maligna do terço superior do esôfago", chapter: "II", block: "C15-C26" },
  { code: "C15.4", description: "Neoplasia maligna do terço médio do esôfago", chapter: "II", block: "C15-C26" },
  { code: "C15.5", description: "Neoplasia maligna do terço inferior do esôfago", chapter: "II", block: "C15-C26" },
  { code: "C15.8", description: "Neoplasia maligna do esôfago com lesão invasiva", chapter: "II", block: "C15-C26" },
  { code: "C15.9", description: "Neoplasia maligna do esôfago, não especificado", chapter: "II", block: "C15-C26" },
  { code: "C16", description: "Neoplasia maligna do estômago", chapter: "II", block: "C15-C26" },
  { code: "C16.0", description: "Neoplasia maligna da cárdia", chapter: "II", block: "C15-C26" },
  { code: "C16.1", description: "Neoplasia maligna do fundo do estômago", chapter: "II", block: "C15-C26" },
  { code: "C16.2", description: "Neoplasia maligna do corpo do estômago", chapter: "II", block: "C15-C26" },
  { code: "C16.3", description: "Neoplasia maligna do antro pilórico", chapter: "II", block: "C15-C26" },
  { code: "C16.4", description: "Neoplasia maligna do piloro", chapter: "II", block: "C15-C26" },
  {
    code: "C16.5",
    description: "Neoplasia maligna da pequena curvatura do estômago, não especificada",
    chapter: "II",
    block: "C15-C26",
  },
  {
    code: "C16.6",
    description: "Neoplasia maligna da grande curvatura do estômago, não especificada",
    chapter: "II",
    block: "C15-C26",
  },
  { code: "C16.8", description: "Neoplasia maligna do estômago com lesão invasiva", chapter: "II", block: "C15-C26" },
  { code: "C16.9", description: "Neoplasia maligna do estômago, não especificado", chapter: "II", block: "C15-C26" },
  { code: "C17", description: "Neoplasia maligna do intestino delgado", chapter: "II", block: "C15-C26" },
  { code: "C18", description: "Neoplasia maligna do cólon", chapter: "II", block: "C15-C26" },
  { code: "C18.0", description: "Neoplasia maligna do ceco", chapter: "II", block: "C15-C26" },
  { code: "C18.1", description: "Neoplasia maligna do apêndice", chapter: "II", block: "C15-C26" },
  { code: "C18.2", description: "Neoplasia maligna do cólon ascendente", chapter: "II", block: "C15-C26" },
  { code: "C18.3", description: "Neoplasia maligna da flexura hepática", chapter: "II", block: "C15-C26" },
  { code: "C18.4", description: "Neoplasia maligna do cólon transverso", chapter: "II", block: "C15-C26" },
  { code: "C18.5", description: "Neoplasia maligna da flexura esplênica", chapter: "II", block: "C15-C26" },
  { code: "C18.6", description: "Neoplasia maligna do cólon descendente", chapter: "II", block: "C15-C26" },
  { code: "C18.7", description: "Neoplasia maligna do cólon sigmoide", chapter: "II", block: "C15-C26" },
  { code: "C18.8", description: "Neoplasia maligna do cólon com lesão invasiva", chapter: "II", block: "C15-C26" },
  { code: "C18.9", description: "Neoplasia maligna do cólon, não especificado", chapter: "II", block: "C15-C26" },
  { code: "C19", description: "Neoplasia maligna da junção retossigmoide", chapter: "II", block: "C15-C26" },
  { code: "C20", description: "Neoplasia maligna do reto", chapter: "II", block: "C15-C26" },
  { code: "C21", description: "Neoplasia maligna do ânus e do canal anal", chapter: "II", block: "C15-C26" },
  {
    code: "C22",
    description: "Neoplasia maligna do fígado e das vias biliares intra-hepáticas",
    chapter: "II",
    block: "C15-C26",
  },
  { code: "C22.0", description: "Carcinoma de células hepáticas", chapter: "II", block: "C15-C26" },
  { code: "C22.1", description: "Carcinoma de vias biliares intra-hepáticas", chapter: "II", block: "C15-C26" },
  { code: "C22.2", description: "Hepatoblastoma", chapter: "II", block: "C15-C26" },
  { code: "C22.3", description: "Angiossarcoma do fígado", chapter: "II", block: "C15-C26" },
  { code: "C22.4", description: "Outros sarcomas do fígado", chapter: "II", block: "C15-C26" },
  { code: "C22.7", description: "Outros carcinomas especificados do fígado", chapter: "II", block: "C15-C26" },
  { code: "C22.9", description: "Neoplasia maligna do fígado, não especificada", chapter: "II", block: "C15-C26" },
  { code: "C23", description: "Neoplasia maligna da vesícula biliar", chapter: "II", block: "C15-C26" },
  {
    code: "C24",
    description: "Neoplasia maligna de outras partes e de partes não especificadas das vias biliares",
    chapter: "II",
    block: "C15-C26",
  },
  { code: "C25", description: "Neoplasia maligna do pâncreas", chapter: "II", block: "C15-C26" },
  { code: "C25.0", description: "Neoplasia maligna da cabeça do pâncreas", chapter: "II", block: "C15-C26" },
  { code: "C25.1", description: "Neoplasia maligna do corpo do pâncreas", chapter: "II", block: "C15-C26" },
  { code: "C25.2", description: "Neoplasia maligna da cauda do pâncreas", chapter: "II", block: "C15-C26" },
  { code: "C25.3", description: "Neoplasia maligna do canal pancreático", chapter: "II", block: "C15-C26" },
  { code: "C25.4", description: "Neoplasia maligna do pâncreas endócrino", chapter: "II", block: "C15-C26" },
  { code: "C25.7", description: "Neoplasia maligna de outras partes do pâncreas", chapter: "II", block: "C15-C26" },
  { code: "C25.8", description: "Neoplasia maligna do pâncreas com lesão invasiva", chapter: "II", block: "C15-C26" },
  { code: "C25.9", description: "Neoplasia maligna do pâncreas, não especificado", chapter: "II", block: "C15-C26" },
  {
    code: "C26",
    description: "Neoplasia maligna de outros órgãos digestivos e de localizações mal definidas no aparelho digestivo",
    chapter: "II",
    block: "C15-C26",
  },

  // Neoplasias malignas do aparelho respiratório (C30-C39)
  {
    code: "C30",
    description: "Neoplasia maligna da cavidade nasal e do ouvido médio",
    chapter: "II",
    block: "C30-C39",
  },
  { code: "C31", description: "Neoplasia maligna dos seios da face", chapter: "II", block: "C30-C39" },
  { code: "C32", description: "Neoplasia maligna da laringe", chapter: "II", block: "C30-C39" },
  { code: "C33", description: "Neoplasia maligna da traqueia", chapter: "II", block: "C30-C39" },
  { code: "C34", description: "Neoplasia maligna dos brônquios e dos pulmões", chapter: "II", block: "C30-C39" },
  { code: "C34.0", description: "Neoplasia maligna do brônquio principal", chapter: "II", block: "C30-C39" },
  {
    code: "C34.1",
    description: "Neoplasia maligna do lobo superior, brônquio ou pulmão",
    chapter: "II",
    block: "C30-C39",
  },
  {
    code: "C34.2",
    description: "Neoplasia maligna do lobo médio, brônquio ou pulmão",
    chapter: "II",
    block: "C30-C39",
  },
  {
    code: "C34.3",
    description: "Neoplasia maligna do lobo inferior, brônquio ou pulmão",
    chapter: "II",
    block: "C30-C39",
  },
  {
    code: "C34.8",
    description: "Neoplasia maligna dos brônquios e dos pulmões com lesão invasiva",
    chapter: "II",
    block: "C30-C39",
  },
  {
    code: "C34.9",
    description: "Neoplasia maligna dos brônquios ou pulmões, não especificado",
    chapter: "II",
    block: "C30-C39",
  },
  { code: "C37", description: "Neoplasia maligna do timo", chapter: "II", block: "C30-C39" },
  { code: "C38", description: "Neoplasia maligna do coração, mediastino e pleura", chapter: "II", block: "C30-C39" },
  {
    code: "C39",
    description: "Neoplasia maligna de outras localizações e de localizações mal definidas do aparelho respiratório",
    chapter: "II",
    block: "C30-C39",
  },

  // Neoplasias malignas da mama (C50)
  { code: "C50", description: "Neoplasia maligna da mama", chapter: "II", block: "C50" },
  { code: "C50.0", description: "Neoplasia maligna do mamilo e aréola", chapter: "II", block: "C50" },
  { code: "C50.1", description: "Neoplasia maligna da porção central da mama", chapter: "II", block: "C50" },
  {
    code: "C50.2",
    description: "Neoplasia maligna do quadrante superior interno da mama",
    chapter: "II",
    block: "C50",
  },
  {
    code: "C50.3",
    description: "Neoplasia maligna do quadrante inferior interno da mama",
    chapter: "II",
    block: "C50",
  },
  {
    code: "C50.4",
    description: "Neoplasia maligna do quadrante superior externo da mama",
    chapter: "II",
    block: "C50",
  },
  {
    code: "C50.5",
    description: "Neoplasia maligna do quadrante inferior externo da mama",
    chapter: "II",
    block: "C50",
  },
  { code: "C50.6", description: "Neoplasia maligna da porção axilar da mama", chapter: "II", block: "C50" },
  { code: "C50.8", description: "Neoplasia maligna da mama com lesão invasiva", chapter: "II", block: "C50" },
  { code: "C50.9", description: "Neoplasia maligna da mama, não especificada", chapter: "II", block: "C50" },

  // Neoplasias malignas dos órgãos genitais femininos (C51-C58)
  { code: "C51", description: "Neoplasia maligna da vulva", chapter: "II", block: "C51-C58" },
  { code: "C52", description: "Neoplasia maligna da vagina", chapter: "II", block: "C51-C58" },
  { code: "C53", description: "Neoplasia maligna do colo do útero", chapter: "II", block: "C51-C58" },
  { code: "C53.0", description: "Neoplasia maligna do endocérvix", chapter: "II", block: "C51-C58" },
  { code: "C53.1", description: "Neoplasia maligna do exocérvix", chapter: "II", block: "C51-C58" },
  {
    code: "C53.8",
    description: "Neoplasia maligna do colo do útero com lesão invasiva",
    chapter: "II",
    block: "C51-C58",
  },
  {
    code: "C53.9",
    description: "Neoplasia maligna do colo do útero, não especificado",
    chapter: "II",
    block: "C51-C58",
  },
  { code: "C54", description: "Neoplasia maligna do corpo do útero", chapter: "II", block: "C51-C58" },
  { code: "C54.0", description: "Neoplasia maligna do istmo do útero", chapter: "II", block: "C51-C58" },
  { code: "C54.1", description: "Neoplasia maligna do endométrio", chapter: "II", block: "C51-C58" },
  { code: "C54.2", description: "Neoplasia maligna do miométrio", chapter: "II", block: "C51-C58" },
  { code: "C54.3", description: "Neoplasia maligna do fundo do útero", chapter: "II", block: "C51-C58" },
  {
    code: "C54.8",
    description: "Neoplasia maligna do corpo do útero com lesão invasiva",
    chapter: "II",
    block: "C51-C58",
  },
  {
    code: "C54.9",
    description: "Neoplasia maligna do corpo do útero, não especificado",
    chapter: "II",
    block: "C51-C58",
  },
  { code: "C55", description: "Neoplasia maligna do útero, porção não especificada", chapter: "II", block: "C51-C58" },
  { code: "C56", description: "Neoplasia maligna do ovário", chapter: "II", block: "C51-C58" },
  {
    code: "C57",
    description: "Neoplasia maligna de outros órgãos genitais femininos e dos não especificados",
    chapter: "II",
    block: "C51-C58",
  },
  { code: "C58", description: "Neoplasia maligna da placenta", chapter: "II", block: "C51-C58" },

  // Neoplasias malignas dos órgãos genitais masculinos (C60-C63)
  { code: "C60", description: "Neoplasia maligna do pênis", chapter: "II", block: "C60-C63" },
  { code: "C61", description: "Neoplasia maligna da próstata", chapter: "II", block: "C60-C63" },
  { code: "C62", description: "Neoplasia maligna dos testículos", chapter: "II", block: "C60-C63" },
  {
    code: "C63",
    description: "Neoplasia maligna de outros órgãos genitais masculinos e dos não especificados",
    chapter: "II",
    block: "C60-C63",
  },

  // Neoplasias malignas do trato urinário (C64-C68)
  { code: "C64", description: "Neoplasia maligna do rim, exceto pelve renal", chapter: "II", block: "C64-C68" },
  { code: "C65", description: "Neoplasia maligna da pelve renal", chapter: "II", block: "C64-C68" },
  { code: "C66", description: "Neoplasia maligna dos ureteres", chapter: "II", block: "C64-C68" },
  { code: "C67", description: "Neoplasia maligna da bexiga", chapter: "II", block: "C64-C68" },
  { code: "C67.0", description: "Neoplasia maligna do trígono da bexiga", chapter: "II", block: "C64-C68" },
  { code: "C67.1", description: "Neoplasia maligna da cúpula da bexiga", chapter: "II", block: "C64-C68" },
  { code: "C67.2", description: "Neoplasia maligna da parede lateral da bexiga", chapter: "II", block: "C64-C68" },
  { code: "C67.3", description: "Neoplasia maligna da parede anterior da bexiga", chapter: "II", block: "C64-C68" },
  { code: "C67.4", description: "Neoplasia maligna da parede posterior da bexiga", chapter: "II", block: "C64-C68" },
  { code: "C67.5", description: "Neoplasia maligna do colo da bexiga", chapter: "II", block: "C64-C68" },
  { code: "C67.6", description: "Neoplasia maligna do orifício ureteral", chapter: "II", block: "C64-C68" },
  { code: "C67.7", description: "Neoplasia maligna do úraco", chapter: "II", block: "C64-C68" },
  { code: "C67.8", description: "Neoplasia maligna da bexiga com lesão invasiva", chapter: "II", block: "C64-C68" },
  { code: "C67.9", description: "Neoplasia maligna da bexiga, não especificada", chapter: "II", block: "C64-C68" },
  {
    code: "C68",
    description: "Neoplasia maligna de outros órgãos urinários e dos não especificados",
    chapter: "II",
    block: "C64-C68",
  },
]

// CID-10 - Capítulo IV - Doenças Endócrinas, Nutricionais e Metabólicas (E00-E90)
const CID10_CAPITULO_IV: CID10Code[] = [
  // Diabetes (E10-E14)
  { code: "E10", description: "Diabetes mellitus insulino-dependente", chapter: "IV", block: "E10-E14" },
  { code: "E10.0", description: "Diabetes mellitus insulino-dependente - com coma", chapter: "IV", block: "E10-E14" },
  {
    code: "E10.1",
    description: "Diabetes mellitus insulino-dependente - com cetoacidose",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E10.2",
    description: "Diabetes mellitus insulino-dependente - com complicações renais",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E10.3",
    description: "Diabetes mellitus insulino-dependente - com complicações oftálmicas",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E10.4",
    description: "Diabetes mellitus insulino-dependente - com complicações neurológicas",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E10.5",
    description: "Diabetes mellitus insulino-dependente - com complicações circulatórias periféricas",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E10.6",
    description: "Diabetes mellitus insulino-dependente - com outras complicações especificadas",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E10.7",
    description: "Diabetes mellitus insulino-dependente - com complicações múltiplas",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E10.8",
    description: "Diabetes mellitus insulino-dependente - com complicações não especificadas",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E10.9",
    description: "Diabetes mellitus insulino-dependente - sem complicações",
    chapter: "IV",
    block: "E10-E14",
  },
  { code: "E11", description: "Diabetes mellitus não-insulino-dependente", chapter: "IV", block: "E10-E14" },
  {
    code: "E11.0",
    description: "Diabetes mellitus não-insulino-dependente - com coma",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E11.1",
    description: "Diabetes mellitus não-insulino-dependente - com cetoacidose",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E11.2",
    description: "Diabetes mellitus não-insulino-dependente - com complicações renais",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E11.3",
    description: "Diabetes mellitus não-insulino-dependente - com complicações oftálmicas",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E11.4",
    description: "Diabetes mellitus não-insulino-dependente - com complicações neurológicas",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E11.5",
    description: "Diabetes mellitus não-insulino-dependente - com complicações circulatórias periféricas",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E11.6",
    description: "Diabetes mellitus não-insulino-dependente - com outras complicações especificadas",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E11.7",
    description: "Diabetes mellitus não-insulino-dependente - com complicações múltiplas",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E11.8",
    description: "Diabetes mellitus não-insulino-dependente - com complicações não especificadas",
    chapter: "IV",
    block: "E10-E14",
  },
  {
    code: "E11.9",
    description: "Diabetes mellitus não-insulino-dependente - sem complicações",
    chapter: "IV",
    block: "E10-E14",
  },
  { code: "E12", description: "Diabetes mellitus relacionado com a desnutrição", chapter: "IV", block: "E10-E14" },
  { code: "E13", description: "Outros tipos especificados de diabetes mellitus", chapter: "IV", block: "E10-E14" },
  { code: "E14", description: "Diabetes mellitus não especificado", chapter: "IV", block: "E10-E14" },

  // Obesidade e Transtornos Nutricionais (E65-E68)
  { code: "E65", description: "Adiposidade localizada", chapter: "IV", block: "E65-E68" },
  { code: "E66", description: "Obesidade", chapter: "IV", block: "E65-E68" },
  { code: "E66.0", description: "Obesidade devida a excesso de calorias", chapter: "IV", block: "E65-E68" },
  { code: "E66.1", description: "Obesidade induzida por drogas", chapter: "IV", block: "E65-E68" },
  { code: "E66.2", description: "Obesidade extrema com hipoventilação alveolar", chapter: "IV", block: "E65-E68" },
  { code: "E66.8", description: "Outra obesidade", chapter: "IV", block: "E65-E68" },
  { code: "E66.9", description: "Obesidade não especificada", chapter: "IV", block: "E65-E68" },

  // Distúrbios Metabólicos (E70-E90)
  {
    code: "E78",
    description: "Distúrbios do metabolismo de lipoproteínas e outras lipidemias",
    chapter: "IV",
    block: "E70-E90",
  },
  { code: "E78.0", description: "Hipercolesterolemia pura", chapter: "IV", block: "E70-E90" },
  { code: "E78.1", description: "Hipertrigliceridemia pura", chapter: "IV", block: "E70-E90" },
  { code: "E78.2", description: "Hiperlipidemia mista", chapter: "IV", block: "E70-E90" },
  { code: "E78.3", description: "Hiperquilomicronemia", chapter: "IV", block: "E70-E90" },
  { code: "E78.4", description: "Outras hiperlipidemias", chapter: "IV", block: "E70-E90" },
  { code: "E78.5", description: "Hiperlipidemia não especificada", chapter: "IV", block: "E70-E90" },
  { code: "E78.6", description: "Deficiência de lipoproteínas", chapter: "IV", block: "E70-E90" },
  { code: "E78.8", description: "Outros distúrbios do metabolismo de lipoproteínas", chapter: "IV", block: "E70-E90" },
  {
    code: "E78.9",
    description: "Distúrbio não especificado do metabolismo de lipoproteínas",
    chapter: "IV",
    block: "E70-E90",
  },

  // Tireoide (E00-E07)
  { code: "E00", description: "Síndrome de deficiência congênita de iodo", chapter: "IV", block: "E00-E07" },
  {
    code: "E01",
    description: "Transtornos tireoidianos e afecções associadas, relacionados à deficiência de iodo",
    chapter: "IV",
    block: "E00-E07",
  },
  { code: "E02", description: "Hipotireoidismo subclínico por deficiência de iodo", chapter: "IV", block: "E00-E07" },
  { code: "E03", description: "Outros hipotireoidismos", chapter: "IV", block: "E00-E07" },
  { code: "E03.0", description: "Hipotireoidismo congênito com bócio difuso", chapter: "IV", block: "E00-E07" },
  { code: "E03.1", description: "Hipotireoidismo congênito sem bócio", chapter: "IV", block: "E00-E07" },
  {
    code: "E03.2",
    description: "Hipotireoidismo devido a medicamentos e a outras substâncias exógenas",
    chapter: "IV",
    block: "E00-E07",
  },
  { code: "E03.3", description: "Hipotireoidismo pós-infeccioso", chapter: "IV", block: "E00-E07" },
  { code: "E03.4", description: "Atrofia (adquirida) da tireóide", chapter: "IV", block: "E00-E07" },
  { code: "E03.5", description: "Coma mixedematoso", chapter: "IV", block: "E00-E07" },
  { code: "E03.8", description: "Outros hipotireoidismos especificados", chapter: "IV", block: "E00-E07" },
  { code: "E03.9", description: "Hipotireoidismo não especificado", chapter: "IV", block: "E00-E07" },
  { code: "E04", description: "Outros bócios não-tóxicos", chapter: "IV", block: "E00-E07" },
  { code: "E05", description: "Tireotoxicose [hipertireoidismo]", chapter: "IV", block: "E00-E07" },
  { code: "E05.0", description: "Tireotoxicose com bócio difuso", chapter: "IV", block: "E00-E07" },
  { code: "E05.1", description: "Tireotoxicose com bócio uninodular tóxico", chapter: "IV", block: "E00-E07" },
  { code: "E05.2", description: "Tireotoxicose com bócio multinodular tóxico", chapter: "IV", block: "E00-E07" },
  { code: "E05.3", description: "Tireotoxicose devida a tecido tireoidiano ectópico", chapter: "IV", block: "E00-E07" },
  { code: "E05.4", description: "Tireotoxicose factícia", chapter: "IV", block: "E00-E07" },
  { code: "E05.5", description: "Crise ou tempestade tireóidea", chapter: "IV", block: "E00-E07" },
  { code: "E05.8", description: "Outras tireotoxicoses", chapter: "IV", block: "E00-E07" },
  { code: "E05.9", description: "Tireotoxicose não especificada", chapter: "IV", block: "E00-E07" },
  { code: "E06", description: "Tireoidite", chapter: "IV", block: "E00-E07" },
  { code: "E06.0", description: "Tireoidite aguda", chapter: "IV", block: "E00-E07" },
  { code: "E06.1", description: "Tireoidite subaguda", chapter: "IV", block: "E00-E07" },
  { code: "E06.2", description: "Tireoidite crônica com tireotoxicose transitória", chapter: "IV", block: "E00-E07" },
  { code: "E06.3", description: "Tireoidite auto-imune", chapter: "IV", block: "E00-E07" },
  { code: "E06.4", description: "Tireoidite induzida por droga", chapter: "IV", block: "E00-E07" },
  { code: "E06.5", description: "Outras tireoidites crônicas", chapter: "IV", block: "E00-E07" },
  { code: "E06.9", description: "Tireoidite não especificada", chapter: "IV", block: "E00-E07" },
  { code: "E07", description: "Outros transtornos da tireóide", chapter: "IV", block: "E00-E07" },
]

// CID-10 - Capítulo V - Transtornos Mentais e Comportamentais (F00-F99)
const CID10_CAPITULO_V: CID10Code[] = [
  // Transtornos do Humor (F30-F39)
  { code: "F30", description: "Episódio maníaco", chapter: "V", block: "F30-F39" },
  { code: "F30.0", description: "Hipomania", chapter: "V", block: "F30-F39" },
  { code: "F30.1", description: "Mania sem sintomas psicóticos", chapter: "V", block: "F30-F39" },
  { code: "F30.2", description: "Mania com sintomas psicóticos", chapter: "V", block: "F30-F39" },
  { code: "F30.8", description: "Outros episódios maníacos", chapter: "V", block: "F30-F39" },
  { code: "F30.9", description: "Episódio maníaco não especificado", chapter: "V", block: "F30-F39" },
  { code: "F31", description: "Transtorno afetivo bipolar", chapter: "V", block: "F30-F39" },
  {
    code: "F31.0",
    description: "Transtorno afetivo bipolar, episódio atual hipomaníaco",
    chapter: "V",
    block: "F30-F39",
  },
  {
    code: "F31.1",
    description: "Transtorno afetivo bipolar, episódio atual maníaco sem sintomas psicóticos",
    chapter: "V",
    block: "F30-F39",
  },
  {
    code: "F31.2",
    description: "Transtorno afetivo bipolar, episódio atual maníaco com sintomas psicóticos",
    chapter: "V",
    block: "F30-F39",
  },
  {
    code: "F31.3",
    description: "Transtorno afetivo bipolar, episódio atual depressivo leve ou moderado",
    chapter: "V",
    block: "F30-F39",
  },
  {
    code: "F31.4",
    description: "Transtorno afetivo bipolar, episódio atual depressivo grave sem sintomas psicóticos",
    chapter: "V",
    block: "F30-F39",
  },
  {
    code: "F31.5",
    description: "Transtorno afetivo bipolar, episódio atual depressivo grave com sintomas psicóticos",
    chapter: "V",
    block: "F30-F39",
  },
  { code: "F31.6", description: "Transtorno afetivo bipolar, episódio atual misto", chapter: "V", block: "F30-F39" },
  { code: "F31.7", description: "Transtorno afetivo bipolar, atualmente em remissão", chapter: "V", block: "F30-F39" },
  { code: "F31.8", description: "Outros transtornos afetivos bipolares", chapter: "V", block: "F30-F39" },
  { code: "F31.9", description: "Transtorno afetivo bipolar não especificado", chapter: "V", block: "F30-F39" },
  { code: "F32", description: "Episódios depressivos", chapter: "V", block: "F30-F39" },
  { code: "F32.0", description: "Episódio depressivo leve", chapter: "V", block: "F30-F39" },
  { code: "F32.1", description: "Episódio depressivo moderado", chapter: "V", block: "F30-F39" },
  { code: "F32.2", description: "Episódio depressivo grave sem sintomas psicóticos", chapter: "V", block: "F30-F39" },
  { code: "F32.3", description: "Episódio depressivo grave com sintomas psicóticos", chapter: "V", block: "F30-F39" },
  { code: "F32.8", description: "Outros episódios depressivos", chapter: "V", block: "F30-F39" },
  { code: "F32.9", description: "Episódio depressivo não especificado", chapter: "V", block: "F30-F39" },
  { code: "F33", description: "Transtorno depressivo recorrente", chapter: "V", block: "F30-F39" },
  {
    code: "F33.0",
    description: "Transtorno depressivo recorrente, episódio atual leve",
    chapter: "V",
    block: "F30-F39",
  },
  {
    code: "F33.1",
    description: "Transtorno depressivo recorrente, episódio atual moderado",
    chapter: "V",
    block: "F30-F39",
  },
  {
    code: "F33.2",
    description: "Transtorno depressivo recorrente, episódio atual grave sem sintomas psicóticos",
    chapter: "V",
    block: "F30-F39",
  },
  {
    code: "F33.3",
    description: "Transtorno depressivo recorrente, episódio atual grave com sintomas psicóticos",
    chapter: "V",
    block: "F30-F39",
  },
  {
    code: "F33.4",
    description: "Transtorno depressivo recorrente, atualmente em remissão",
    chapter: "V",
    block: "F30-F39",
  },
  { code: "F33.8", description: "Outros transtornos depressivos recorrentes", chapter: "V", block: "F30-F39" },
  { code: "F33.9", description: "Transtorno depressivo recorrente sem especificação", chapter: "V", block: "F30-F39" },
  { code: "F34", description: "Transtornos de humor [afetivos] persistentes", chapter: "V", block: "F30-F39" },
  { code: "F34.0", description: "Ciclotimia", chapter: "V", block: "F30-F39" },
  { code: "F34.1", description: "Distimia", chapter: "V", block: "F30-F39" },
  { code: "F34.8", description: "Outros transtornos do humor [afetivos] persistentes", chapter: "V", block: "F30-F39" },
  {
    code: "F34.9",
    description: "Transtorno do humor [afetivo] persistente não especificado",
    chapter: "V",
    block: "F30-F39",
  },

  // Transtornos Ansiosos (F40-F48)
  { code: "F40", description: "Transtornos fóbico-ansiosos", chapter: "V", block: "F40-F48" },
  { code: "F40.0", description: "Agorafobia", chapter: "V", block: "F40-F48" },
  { code: "F40.1", description: "Fobias sociais", chapter: "V", block: "F40-F48" },
  { code: "F40.2", description: "Fobias específicas (isoladas)", chapter: "V", block: "F40-F48" },
  { code: "F40.8", description: "Outros transtornos fóbico-ansiosos", chapter: "V", block: "F40-F48" },
  { code: "F40.9", description: "Transtorno fóbico-ansioso não especificado", chapter: "V", block: "F40-F48" },
  { code: "F41", description: "Outros transtornos ansiosos", chapter: "V", block: "F40-F48" },
  {
    code: "F41.0",
    description: "Transtorno de pânico [ansiedade paroxística episódica]",
    chapter: "V",
    block: "F40-F48",
  },
  { code: "F41.1", description: "Ansiedade generalizada", chapter: "V", block: "F40-F48" },
  { code: "F41.2", description: "Transtorno misto ansioso e depressivo", chapter: "V", block: "F40-F48" },
  { code: "F41.3", description: "Outros transtornos ansiosos mistos", chapter: "V", block: "F40-F48" },
  { code: "F41.8", description: "Outros transtornos ansiosos especificados", chapter: "V", block: "F40-F48" },
  { code: "F41.9", description: "Transtorno ansioso não especificado", chapter: "V", block: "F40-F48" },
  { code: "F42", description: "Transtorno obsessivo-compulsivo", chapter: "V", block: "F40-F48" },
  {
    code: "F42.0",
    description: "Transtorno obsessivo-compulsivo com predominância de ideias ou de ruminações obsessivas",
    chapter: "V",
    block: "F40-F48",
  },
  {
    code: "F42.1",
    description: "Transtorno obsessivo-compulsivo com predominância de comportamentos compulsivos [rituais obsessivos]",
    chapter: "V",
    block: "F40-F48",
  },
  {
    code: "F42.2",
    description: "Transtorno obsessivo-compulsivo, forma mista, com ideias obsessivas e comportamentos compulsivos",
    chapter: "V",
    block: "F40-F48",
  },
  { code: "F42.8", description: "Outros transtornos obsessivo-compulsivos", chapter: "V", block: "F40-F48" },
  { code: "F42.9", description: "Transtorno obsessivo-compulsivo não especificado", chapter: "V", block: "F40-F48" },
  { code: "F43", description: "Reações ao estresse grave e transtornos de adaptação", chapter: "V", block: "F40-F48" },
  { code: "F43.0", description: "Reação aguda ao estresse", chapter: "V", block: "F40-F48" },
  { code: "F43.1", description: "Estado de estresse pós-traumático", chapter: "V", block: "F40-F48" },
  { code: "F43.2", description: "Transtornos de adaptação", chapter: "V", block: "F40-F48" },
  { code: "F43.8", description: "Outras reações ao estresse grave", chapter: "V", block: "F40-F48" },
  { code: "F43.9", description: "Reação não especificada a um estresse grave", chapter: "V", block: "F40-F48" },
]

// Combina todos os capítulos CID-10
export const ALL_CID10_CODES: CID10Code[] = [...CID10_CAPITULO_I, ...CID10_CAPITULO_II, ...CID10_CAPITULO_V]

// CID-11 básico (estrutura simplificada)
export const CID11_CODES: CID11Code[] = [
  { code: "1A00", description: "Doenças gastrointestinais infecciosas", chapter: "1" },
  { code: "1A01", description: "Cólera", chapter: "1" },
  { code: "1A02", description: "Febre tifoide", chapter: "1" },
  { code: "1A03", description: "Febre paratifoide", chapter: "1" },
  { code: "1A04", description: "Outras salmoneloses", chapter: "1" },
  { code: "1A05", description: "Shigelose", chapter: "1" },
  { code: "1A06", description: "Amebíase", chapter: "1" },
  { code: "2A00", description: "Neoplasias malignas primárias", chapter: "2" },
  { code: "2A01", description: "Neoplasias malignas secundárias", chapter: "2" },
  { code: "2A02", description: "Neoplasias in situ", chapter: "2" },
  { code: "2A03", description: "Neoplasias benignas", chapter: "2" },
  { code: "5A00", description: "Transtornos do neurodesenvolvimento", chapter: "5" },
  { code: "5A01", description: "Esquizofrenia e outras perturbações psicóticas primárias", chapter: "5" },
  { code: "5A02", description: "Catatonia", chapter: "5" },
  { code: "6A00", description: "Transtornos de humor", chapter: "6" },
  { code: "6A01", description: "Transtornos bipolares", chapter: "6" },
  { code: "6A02", description: "Transtornos depressivos", chapter: "6" },
  { code: "6B00", description: "Transtornos de ansiedade ou relacionados ao medo", chapter: "6" },
  { code: "6B01", description: "Transtorno de ansiedade generalizada", chapter: "6" },
  { code: "6B02", description: "Transtorno de pânico", chapter: "6" },
  { code: "6B03", description: "Agorafobia", chapter: "6" },
  { code: "6B04", description: "Fobia específica", chapter: "6" },
  { code: "6B05", description: "Transtorno de ansiedade social", chapter: "6" },
]

// Capítulos CID-10
export const CID10_CHAPTERS = [
  { code: "I", name: "Doenças infecciosas e parasitárias", range: "A00-B99" },
  { code: "II", name: "Neoplasias", range: "C00-D48" },
  { code: "III", name: "Doenças do sangue e órgãos hematopoéticos", range: "D50-D89" },
  { code: "IV", name: "Doenças endócrinas, nutricionais e metabólicas", range: "E00-E90" },
  { code: "V", name: "Transtornos mentais e comportamentais", range: "F00-F99" },
  { code: "VI", name: "Doenças do sistema nervoso", range: "G00-G99" },
  { code: "VII", name: "Doenças do olho e anexos", range: "H00-H59" },
  { code: "VIII", name: "Doenças do ouvido e da apófise mastóide", range: "H60-H95" },
  { code: "IX", name: "Doenças do aparelho circulatório", range: "I00-I99" },
  { code: "X", name: "Doenças do aparelho respiratório", range: "J00-J99" },
  { code: "XI", name: "Doenças do aparelho digestivo", range: "K00-K93" },
  { code: "XII", name: "Doenças da pele e do tecido subcutâneo", range: "L00-L99" },
  { code: "XIII", name: "Doenças do sistema osteomuscular e tecido conjuntivo", range: "M00-M99" },
  { code: "XIV", name: "Doenças do aparelho geniturinário", range: "N00-N99" },
  { code: "XV", name: "Gravidez, parto e puerpério", range: "O00-O99" },
  { code: "XVI", name: "Afecções originadas no período perinatal", range: "P00-P96" },
  { code: "XVII", name: "Malformações congênitas", range: "Q00-Q99" },
  { code: "XVIII", name: "Sintomas, sinais e achados anormais", range: "R00-R99" },
  { code: "XIX", name: "Lesões, envenenamentos e causas externas", range: "S00-T98" },
  { code: "XX", name: "Causas externas de morbidade e mortalidade", range: "V01-Y98" },
  { code: "XXI", name: "Fatores que influenciam o estado de saúde", range: "Z00-Z99" },
] as const

// Função de busca CID-10
export function searchCID10(query: string, limit = 50): CID10Code[] {
  const normalizedQuery = query.toLowerCase().trim()

  if (!normalizedQuery) return ALL_CID10_CODES.slice(0, limit)

  // Busca por código exato primeiro
  const exactMatch = ALL_CID10_CODES.filter((cid) => cid.code.toLowerCase() === normalizedQuery)
  if (exactMatch.length > 0) return exactMatch

  // Busca por código parcial ou descrição
  return ALL_CID10_CODES.filter(
    (cid) =>
      cid.code.toLowerCase().includes(normalizedQuery) || cid.description.toLowerCase().includes(normalizedQuery),
  ).slice(0, limit)
}

// Função de busca CID-11
export function searchCID11(query: string, limit = 50): CID11Code[] {
  const normalizedQuery = query.toLowerCase().trim()

  if (!normalizedQuery) return CID11_CODES.slice(0, limit)

  return CID11_CODES.filter(
    (cid) =>
      cid.code.toLowerCase().includes(normalizedQuery) || cid.description.toLowerCase().includes(normalizedQuery),
  ).slice(0, limit)
}

// Obter CID por código
export function getCID10ByCode(code: string): CID10Code | undefined {
  return ALL_CID10_CODES.find((cid) => cid.code === code)
}

// Total de códigos
export const TOTAL_CID10_CODES = ALL_CID10_CODES.length
export const TOTAL_CID11_CODES = CID11_CODES.length
