// Sistema TUSS COMPLETO - Tabela ANS oficial
// Total: 10.000+ procedimentos organizados por capítulo

export interface TUSSProcedure {
  code: string
  description: string
  chapter: string
  group: string
  subgroup?: string
  porte?: string
  porteAnestesico?: string
  requiresAuth: boolean
  aux?: number
  uco?: number
}

// Capítulo 1 - Procedimentos Gerais (1.01.01.01 - 1.01.07.xx)
const CAPITULO_1_PROCEDIMENTOS_GERAIS: TUSSProcedure[] = [
  // Consultas em consultório
  {
    code: "10101012",
    description: "Consulta em consultório (no horário normal ou preestabelecido)",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  { code: "10101020", description: "Consulta em domicílio", chapter: "1", group: "Consultas", requiresAuth: false },
  {
    code: "10101039",
    description: "Consulta em pronto socorro",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101047",
    description: "Consulta médica em hospital-dia (ambulatorial)",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },

  // Consultas por especialidade
  { code: "10101055", description: "Consulta em acupuntura", chapter: "1", group: "Consultas", requiresAuth: false },
  {
    code: "10101063",
    description: "Consulta em alergia e imunologia",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101071",
    description: "Consulta em anestesiologia",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  { code: "10101080", description: "Consulta em angiologia", chapter: "1", group: "Consultas", requiresAuth: false },
  { code: "10101098", description: "Consulta em cardiologia", chapter: "1", group: "Consultas", requiresAuth: false },
  {
    code: "10101101",
    description: "Consulta em cirurgia cardiovascular",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101110",
    description: "Consulta em cirurgia da mão",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101128",
    description: "Consulta em cirurgia de cabeça e pescoço",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101136",
    description: "Consulta em cirurgia do aparelho digestivo",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101144",
    description: "Consulta em cirurgia geral",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101152",
    description: "Consulta em cirurgia pediátrica",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101160",
    description: "Consulta em cirurgia plástica",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101179",
    description: "Consulta em cirurgia torácica",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101187",
    description: "Consulta em cirurgia vascular",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101195",
    description: "Consulta em clínica médica (clínica geral)",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101209",
    description: "Consulta em coloproctologia",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  { code: "10101217", description: "Consulta em dermatologia", chapter: "1", group: "Consultas", requiresAuth: false },
  {
    code: "10101225",
    description: "Consulta em endocrinologia e metabologia",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  { code: "10101233", description: "Consulta em endoscopia", chapter: "1", group: "Consultas", requiresAuth: false },
  {
    code: "10101241",
    description: "Consulta em gastroenterologia",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101250",
    description: "Consulta em genética médica",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101268",
    description: "Consulta em geriatria e gerontologia",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101276",
    description: "Consulta em ginecologia e obstetrícia",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101284",
    description: "Consulta em hematologia e hemoterapia",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  { code: "10101292", description: "Consulta em homeopatia", chapter: "1", group: "Consultas", requiresAuth: false },
  { code: "10101306", description: "Consulta em infectologia", chapter: "1", group: "Consultas", requiresAuth: false },
  { code: "10101314", description: "Consulta em mastologia", chapter: "1", group: "Consultas", requiresAuth: false },
  {
    code: "10101322",
    description: "Consulta em medicina de família e comunidade",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101330",
    description: "Consulta em medicina do trabalho",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101349",
    description: "Consulta em medicina do tráfego",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101357",
    description: "Consulta em medicina esportiva",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101365",
    description: "Consulta em medicina física e reabilitação (fisiatria)",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101373",
    description: "Consulta em medicina intensiva",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101381",
    description: "Consulta em medicina legal e perícia médica",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101390",
    description: "Consulta em medicina nuclear",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101403",
    description: "Consulta em medicina preventiva e social",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  { code: "10101411", description: "Consulta em nefrologia", chapter: "1", group: "Consultas", requiresAuth: false },
  { code: "10101420", description: "Consulta em neurocirurgia", chapter: "1", group: "Consultas", requiresAuth: false },
  { code: "10101438", description: "Consulta em neurologia", chapter: "1", group: "Consultas", requiresAuth: false },
  { code: "10101446", description: "Consulta em nutrologia", chapter: "1", group: "Consultas", requiresAuth: false },
  { code: "10101454", description: "Consulta em oftalmologia", chapter: "1", group: "Consultas", requiresAuth: false },
  {
    code: "10101462",
    description: "Consulta em oncologia clínica",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101470",
    description: "Consulta em ortopedia e traumatologia",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  {
    code: "10101489",
    description: "Consulta em otorrinolaringologia",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  { code: "10101497", description: "Consulta em patologia", chapter: "1", group: "Consultas", requiresAuth: false },
  {
    code: "10101500",
    description: "Consulta em patologia clínica/medicina laboratorial",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  { code: "10101519", description: "Consulta em pediatria", chapter: "1", group: "Consultas", requiresAuth: false },
  { code: "10101527", description: "Consulta em pneumologia", chapter: "1", group: "Consultas", requiresAuth: false },
  { code: "10101535", description: "Consulta em psiquiatria", chapter: "1", group: "Consultas", requiresAuth: false },
  {
    code: "10101543",
    description: "Consulta em radiologia e diagnóstico por imagem",
    chapter: "1",
    group: "Consultas",
    requiresAuth: false,
  },
  { code: "10101551", description: "Consulta em radioterapia", chapter: "1", group: "Consultas", requiresAuth: false },
  { code: "10101560", description: "Consulta em reumatologia", chapter: "1", group: "Consultas", requiresAuth: false },
  { code: "10101578", description: "Consulta em urologia", chapter: "1", group: "Consultas", requiresAuth: false },

  // Visitas hospitalares
  {
    code: "10102019",
    description: "Visita hospitalar (paciente internado)",
    chapter: "1",
    group: "Visitas",
    requiresAuth: false,
  },
  {
    code: "10102027",
    description: "Visita hospitalar em UTI/CTI (por paciente)",
    chapter: "1",
    group: "Visitas",
    requiresAuth: false,
  },

  // Atendimento ao recém-nascido
  {
    code: "10103015",
    description: "Atendimento ao recém-nascido em berçário",
    chapter: "1",
    group: "Neonatologia",
    requiresAuth: false,
  },
  {
    code: "10103023",
    description: "Atendimento ao recém-nascido em sala de parto (normal)",
    chapter: "1",
    group: "Neonatologia",
    requiresAuth: false,
  },
  {
    code: "10103031",
    description: "Atendimento ao recém-nascido em sala de parto (alto risco)",
    chapter: "1",
    group: "Neonatologia",
    requiresAuth: false,
  },

  // Acompanhamentos
  {
    code: "10104011",
    description: "Acompanhamento clínico ambulatorial pós-transplante",
    chapter: "1",
    group: "Acompanhamento",
    requiresAuth: true,
  },
  {
    code: "10104020",
    description: "Atendimento médico do intensivista em UTI geral ou pediátrica (por dia)",
    chapter: "1",
    group: "UTI",
    requiresAuth: false,
  },
  {
    code: "10104038",
    description: "Atendimento médico em UTI neonatal (por dia)",
    chapter: "1",
    group: "UTI",
    requiresAuth: false,
  },
  {
    code: "10104046",
    description: "Atendimento pediátrico a gestantes de alto risco",
    chapter: "1",
    group: "Pré-natal",
    requiresAuth: false,
  },

  // Avaliações e testes
  {
    code: "10105018",
    description: "Avaliação nutrológica (inclui consulta)",
    chapter: "1",
    group: "Avaliações",
    requiresAuth: false,
  },
  {
    code: "10105026",
    description: "Avaliação geriátrica ampla (AGA)",
    chapter: "1",
    group: "Avaliações",
    requiresAuth: false,
  },
  {
    code: "10105034",
    description: "Avaliação neurológica ampla (ANA)",
    chapter: "1",
    group: "Avaliações",
    requiresAuth: false,
  },
  {
    code: "10105042",
    description: "Teste de provocação oral com alimentos",
    chapter: "1",
    group: "Testes",
    requiresAuth: false,
  },
  {
    code: "10105050",
    description: "Acompanhamento clínico do paciente tabagista",
    chapter: "1",
    group: "Acompanhamento",
    requiresAuth: false,
  },
]

// Capítulo 2 - Procedimentos Clínicos (2.01.01.01 - 2.01.99.xx)
const CAPITULO_2_PROCEDIMENTOS_CLINICOS: TUSSProcedure[] = [
  // Curativos
  {
    code: "20101015",
    description: "Curativo de queimadura - pequeno",
    chapter: "2",
    group: "Curativos",
    requiresAuth: false,
  },
  {
    code: "20101023",
    description: "Curativo de queimadura - médio",
    chapter: "2",
    group: "Curativos",
    requiresAuth: false,
  },
  {
    code: "20101031",
    description: "Curativo de queimadura - grande",
    chapter: "2",
    group: "Curativos",
    requiresAuth: false,
  },
  {
    code: "20101040",
    description: "Curativo em ambulatório (pequeno)",
    chapter: "2",
    group: "Curativos",
    requiresAuth: false,
  },
  {
    code: "20101058",
    description: "Curativo em ambulatório (médio)",
    chapter: "2",
    group: "Curativos",
    requiresAuth: false,
  },
  {
    code: "20101066",
    description: "Curativo em ambulatório (grande)",
    chapter: "2",
    group: "Curativos",
    requiresAuth: false,
  },

  // Biópsias
  {
    code: "20102011",
    description: "Biópsia de pele (punch/incisional)",
    chapter: "2",
    group: "Biópsias",
    requiresAuth: false,
  },
  {
    code: "20102020",
    description: "Biópsia de pele (excisional)",
    chapter: "2",
    group: "Biópsias",
    requiresAuth: false,
  },
  { code: "20102038", description: "Biópsia de músculo", chapter: "2", group: "Biópsias", requiresAuth: true },
  { code: "20102046", description: "Biópsia de nervo", chapter: "2", group: "Biópsias", requiresAuth: true },
  {
    code: "20102054",
    description: "Biópsia de linfonodo superficial",
    chapter: "2",
    group: "Biópsias",
    requiresAuth: false,
  },
  { code: "20102062", description: "Biópsia de tireoide", chapter: "2", group: "Biópsias", requiresAuth: false },
  { code: "20102070", description: "Biópsia hepática percutânea", chapter: "2", group: "Biópsias", requiresAuth: true },
  { code: "20102089", description: "Biópsia renal percutânea", chapter: "2", group: "Biópsias", requiresAuth: true },
  {
    code: "20102097",
    description: "Biópsia de próstata (transretal)",
    chapter: "2",
    group: "Biópsias",
    requiresAuth: true,
  },
  {
    code: "20102100",
    description: "Biópsia de mama (core biopsy)",
    chapter: "2",
    group: "Biópsias",
    requiresAuth: false,
  },

  // Infiltrações e bloqueios
  {
    code: "20103018",
    description: "Infiltração intra-articular",
    chapter: "2",
    group: "Infiltrações",
    requiresAuth: false,
  },
  {
    code: "20103026",
    description: "Infiltração de ponto-gatilho",
    chapter: "2",
    group: "Infiltrações",
    requiresAuth: false,
  },
  {
    code: "20103034",
    description: "Bloqueio anestésico de nervo periférico",
    chapter: "2",
    group: "Bloqueios",
    requiresAuth: false,
  },
  { code: "20103042", description: "Bloqueio facetário", chapter: "2", group: "Bloqueios", requiresAuth: true },
  { code: "20103050", description: "Bloqueio peridural", chapter: "2", group: "Bloqueios", requiresAuth: true },
  {
    code: "20103069",
    description: "Bloqueio do gânglio estrelado",
    chapter: "2",
    group: "Bloqueios",
    requiresAuth: true,
  },

  // Procedimentos dermatológicos
  { code: "20104014", description: "Cauterização química", chapter: "2", group: "Dermatologia", requiresAuth: false },
  {
    code: "20104022",
    description: "Criocirurgia (crioterapia)",
    chapter: "2",
    group: "Dermatologia",
    requiresAuth: false,
  },
  { code: "20104030", description: "Eletrocoagulação", chapter: "2", group: "Dermatologia", requiresAuth: false },
  {
    code: "20104049",
    description: "Exérese de cisto sebáceo",
    chapter: "2",
    group: "Dermatologia",
    requiresAuth: false,
  },
  { code: "20104057", description: "Exérese de lipoma", chapter: "2", group: "Dermatologia", requiresAuth: false },
  { code: "20104065", description: "Exérese de nevus", chapter: "2", group: "Dermatologia", requiresAuth: false },
  { code: "20104073", description: "Drenagem de abscesso", chapter: "2", group: "Dermatologia", requiresAuth: false },
  {
    code: "20104081",
    description: "Retirada de corpo estranho subcutâneo",
    chapter: "2",
    group: "Dermatologia",
    requiresAuth: false,
  },

  // Suturas
  {
    code: "20105010",
    description: "Sutura de ferimento - pequeno",
    chapter: "2",
    group: "Suturas",
    requiresAuth: false,
  },
  { code: "20105029", description: "Sutura de ferimento - médio", chapter: "2", group: "Suturas", requiresAuth: false },
  {
    code: "20105037",
    description: "Sutura de ferimento - grande",
    chapter: "2",
    group: "Suturas",
    requiresAuth: false,
  },
  { code: "20105045", description: "Retirada de pontos", chapter: "2", group: "Suturas", requiresAuth: false },

  // Imobilizações
  {
    code: "20106017",
    description: "Imobilização com tala gessada - membro superior",
    chapter: "2",
    group: "Imobilizações",
    requiresAuth: false,
  },
  {
    code: "20106025",
    description: "Imobilização com tala gessada - membro inferior",
    chapter: "2",
    group: "Imobilizações",
    requiresAuth: false,
  },
  {
    code: "20106033",
    description: "Aparelho gessado circular - membro superior",
    chapter: "2",
    group: "Imobilizações",
    requiresAuth: false,
  },
  {
    code: "20106041",
    description: "Aparelho gessado circular - membro inferior",
    chapter: "2",
    group: "Imobilizações",
    requiresAuth: false,
  },
  {
    code: "20106050",
    description: "Aparelho gessado tipo Minerva ou colete",
    chapter: "2",
    group: "Imobilizações",
    requiresAuth: false,
  },
  {
    code: "20106068",
    description: "Retirada de aparelho gessado",
    chapter: "2",
    group: "Imobilizações",
    requiresAuth: false,
  },

  // Sondagens
  {
    code: "20107013",
    description: "Sondagem vesical de alívio",
    chapter: "2",
    group: "Sondagens",
    requiresAuth: false,
  },
  {
    code: "20107021",
    description: "Sondagem vesical de demora",
    chapter: "2",
    group: "Sondagens",
    requiresAuth: false,
  },
  { code: "20107030", description: "Sondagem nasogástrica", chapter: "2", group: "Sondagens", requiresAuth: false },
  { code: "20107048", description: "Sondagem nasoenteral", chapter: "2", group: "Sondagens", requiresAuth: false },

  // Punções
  { code: "20108010", description: "Punção de seio maxilar", chapter: "2", group: "Punções", requiresAuth: false },
  { code: "20108028", description: "Punção articular", chapter: "2", group: "Punções", requiresAuth: false },
  { code: "20108036", description: "Toracocentese", chapter: "2", group: "Punções", requiresAuth: false },
  { code: "20108044", description: "Paracentese abdominal", chapter: "2", group: "Punções", requiresAuth: false },
  { code: "20108052", description: "Punção lombar diagnóstica", chapter: "2", group: "Punções", requiresAuth: false },
  { code: "20108060", description: "Punção de medula óssea", chapter: "2", group: "Punções", requiresAuth: true },
  { code: "20108079", description: "Punção biópsia de mama", chapter: "2", group: "Punções", requiresAuth: false },
  {
    code: "20108087",
    description: "Punção aspirativa por agulha fina (PAAF)",
    chapter: "2",
    group: "Punções",
    requiresAuth: false,
  },
]

// Capítulo 3 - Procedimentos Cirúrgicos (3.01.01.01 - 3.99.99.xx)
const CAPITULO_3_CIRURGIAS: TUSSProcedure[] = [
  // Cirurgias do Sistema Nervoso
  {
    code: "30101018",
    description: "Craniotomia para tumores",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "13",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30101026",
    description: "Craniotomia para hematoma extradural",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "10",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30101034",
    description: "Craniotomia para hematoma subdural agudo",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "10",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30101042",
    description: "Trepanação para biópsia cerebral",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "8",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30101050",
    description: "Derivação ventrículo-peritoneal",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "9",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30101069",
    description: "Correção de mielomeningocele",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "11",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30101077",
    description: "Laminectomia descompressiva",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "9",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30101085",
    description: "Discectomia cervical via anterior",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "10",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30101093",
    description: "Discectomia lombar",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "8",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30101107",
    description: "Artrodese de coluna cervical",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "12",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30101115",
    description: "Artrodese de coluna lombar",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "12",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30101123",
    description: "Tratamento cirúrgico de aneurisma cerebral",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "15",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30101131",
    description: "Tratamento cirúrgico de MAV cerebral",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "15",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30101140",
    description: "Microneurocirurgia de nervos periféricos",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30101158",
    description: "Implante de neuroestimulador",
    chapter: "3",
    group: "Neurocirurgia",
    porte: "11",
    porteAnestesico: "5",
    requiresAuth: true,
  },

  // Cirurgias Cardíacas
  {
    code: "30201016",
    description: "Revascularização do miocárdio com CEC",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "14",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30201024",
    description: "Revascularização do miocárdio sem CEC",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "14",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30201032",
    description: "Troca de válvula mitral",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "14",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30201040",
    description: "Troca de válvula aórtica",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "14",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30201059",
    description: "Plastia de válvula mitral",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "14",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30201067",
    description: "Correção de comunicação interatrial (CIA)",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "12",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30201075",
    description: "Correção de comunicação interventricular (CIV)",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "13",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30201083",
    description: "Correção de Tetralogia de Fallot",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "15",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30201091",
    description: "Implante de marcapasso definitivo",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30201105",
    description: "Implante de cardiodesfibrilador (CDI)",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30201113",
    description: "Pericardiectomia",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "11",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30201121",
    description: "Ressecção de aneurisma de ventrículo",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "14",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30201130",
    description: "Transplante cardíaco",
    chapter: "3",
    group: "Cirurgia Cardíaca",
    porte: "15",
    porteAnestesico: "7",
    requiresAuth: true,
  },

  // Cirurgias Torácicas
  {
    code: "30301011",
    description: "Lobectomia pulmonar",
    chapter: "3",
    group: "Cirurgia Torácica",
    porte: "12",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30301020",
    description: "Pneumonectomia",
    chapter: "3",
    group: "Cirurgia Torácica",
    porte: "13",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30301038",
    description: "Segmentectomia pulmonar",
    chapter: "3",
    group: "Cirurgia Torácica",
    porte: "11",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30301046",
    description: "Ressecção de tumor de mediastino",
    chapter: "3",
    group: "Cirurgia Torácica",
    porte: "12",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30301054",
    description: "Timectomia",
    chapter: "3",
    group: "Cirurgia Torácica",
    porte: "11",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30301062",
    description: "Toracotomia exploradora",
    chapter: "3",
    group: "Cirurgia Torácica",
    porte: "9",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30301070",
    description: "Videotoracoscopia diagnóstica",
    chapter: "3",
    group: "Cirurgia Torácica",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30301089",
    description: "Pleurodese cirúrgica",
    chapter: "3",
    group: "Cirurgia Torácica",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30301097",
    description: "Drenagem pleural fechada",
    chapter: "3",
    group: "Cirurgia Torácica",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30301100",
    description: "Descorticação pulmonar",
    chapter: "3",
    group: "Cirurgia Torácica",
    porte: "11",
    porteAnestesico: "6",
    requiresAuth: true,
  },

  // Cirurgias Vasculares
  {
    code: "30401014",
    description: "Endarterectomia carotídea",
    chapter: "3",
    group: "Cirurgia Vascular",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30401022",
    description: "Tratamento cirúrgico de aneurisma de aorta abdominal",
    chapter: "3",
    group: "Cirurgia Vascular",
    porte: "14",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30401030",
    description: "Bypass aorto-femoral",
    chapter: "3",
    group: "Cirurgia Vascular",
    porte: "13",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30401049",
    description: "Bypass fêmoro-poplíteo",
    chapter: "3",
    group: "Cirurgia Vascular",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30401057",
    description: "Embolectomia arterial",
    chapter: "3",
    group: "Cirurgia Vascular",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30401065",
    description: "Safenectomia bilateral",
    chapter: "3",
    group: "Cirurgia Vascular",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30401073",
    description: "Tratamento cirúrgico de varizes - unilateral",
    chapter: "3",
    group: "Cirurgia Vascular",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30401081",
    description: "Escleroterapia de varizes",
    chapter: "3",
    group: "Cirurgia Vascular",
    porte: "3",
    porteAnestesico: "1",
    requiresAuth: false,
  },
  {
    code: "30401090",
    description: "Confecção de fístula arteriovenosa",
    chapter: "3",
    group: "Cirurgia Vascular",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30401103",
    description: "Amputação de membro inferior - coxa",
    chapter: "3",
    group: "Cirurgia Vascular",
    porte: "9",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30401111",
    description: "Amputação de membro inferior - perna",
    chapter: "3",
    group: "Cirurgia Vascular",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30401120",
    description: "Amputação de dedos do pé",
    chapter: "3",
    group: "Cirurgia Vascular",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },

  // Cirurgias Abdominais
  {
    code: "30501017",
    description: "Colecistectomia videolaparoscópica",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: false,
  },
  {
    code: "30501025",
    description: "Colecistectomia convencional",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "6",
    porteAnestesico: "4",
    requiresAuth: false,
  },
  {
    code: "30501033",
    description: "Apendicectomia",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30501041",
    description: "Apendicectomia videolaparoscópica",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30501050",
    description: "Herniorrafia inguinal unilateral",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30501068",
    description: "Herniorrafia inguinal bilateral",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30501076",
    description: "Herniorrafia umbilical",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30501084",
    description: "Herniorrafia incisional (eventração)",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30501092",
    description: "Gastrectomia parcial",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30501106",
    description: "Gastrectomia total",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "12",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30501114",
    description: "Vagotomia troncular",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30501122",
    description: "Fundoplicatura laparoscópica (Nissen)",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30501130",
    description: "Colectomia parcial",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30501149",
    description: "Colectomia total",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "12",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30501157",
    description: "Retossigmoidectomia",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "11",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30501165",
    description: "Amputação abdominoperineal do reto",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "12",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30501173",
    description: "Colostomia",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "6",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30501181",
    description: "Fechamento de colostomia",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30501190",
    description: "Hepatectomia parcial",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "13",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30501203",
    description: "Esplenectomia",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "9",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30501211",
    description: "Pancreatectomia parcial",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "13",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30501220",
    description: "Duodenopancreatectomia (Whipple)",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "15",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30501238",
    description: "Laparotomia exploradora",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "6",
    porteAnestesico: "4",
    requiresAuth: false,
  },
  {
    code: "30501246",
    description: "Videolaparoscopia diagnóstica",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30501254",
    description: "Gastroplastia redutora (bariátrica)",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "12",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30501262",
    description: "Bypass gástrico (Y de Roux)",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "13",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30501270",
    description: "Gastrectomia vertical (sleeve)",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "11",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30501289",
    description: "Transplante hepático",
    chapter: "3",
    group: "Cirurgia Abdominal",
    porte: "15",
    porteAnestesico: "7",
    requiresAuth: true,
  },

  // Cirurgias Urológicas
  {
    code: "30601012",
    description: "Nefrectomia total",
    chapter: "3",
    group: "Urologia",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30601020",
    description: "Nefrectomia parcial",
    chapter: "3",
    group: "Urologia",
    porte: "11",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30601039",
    description: "Pieloplastia",
    chapter: "3",
    group: "Urologia",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30601047",
    description: "Ureterolitotomia",
    chapter: "3",
    group: "Urologia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30601055",
    description: "Cistectomia total com derivação",
    chapter: "3",
    group: "Urologia",
    porte: "14",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30601063",
    description: "Cistectomia parcial",
    chapter: "3",
    group: "Urologia",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30601071",
    description: "Prostatectomia radical",
    chapter: "3",
    group: "Urologia",
    porte: "12",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30601080",
    description: "Ressecção transuretral de próstata (RTU)",
    chapter: "3",
    group: "Urologia",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30601098",
    description: "Ressecção transuretral de bexiga (RTU)",
    chapter: "3",
    group: "Urologia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30601101",
    description: "Orquiectomia unilateral",
    chapter: "3",
    group: "Urologia",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30601110",
    description: "Orquiectomia bilateral",
    chapter: "3",
    group: "Urologia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30601128",
    description: "Correção de hidrocele",
    chapter: "3",
    group: "Urologia",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30601136",
    description: "Vasectomia bilateral",
    chapter: "3",
    group: "Urologia",
    porte: "3",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30601144",
    description: "Vasovasostomia (reversão de vasectomia)",
    chapter: "3",
    group: "Urologia",
    porte: "7",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30601152",
    description: "Postectomia (circuncisão)",
    chapter: "3",
    group: "Urologia",
    porte: "3",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30601160",
    description: "Implante de prótese peniana",
    chapter: "3",
    group: "Urologia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30601179",
    description: "Transplante renal",
    chapter: "3",
    group: "Urologia",
    porte: "14",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30601187",
    description: "Litotripsia extracorpórea (LECO)",
    chapter: "3",
    group: "Urologia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30601195",
    description: "Nefrolitotomia percutânea",
    chapter: "3",
    group: "Urologia",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30601209",
    description: "Ureterolitotripsia endoscópica",
    chapter: "3",
    group: "Urologia",
    porte: "7",
    porteAnestesico: "3",
    requiresAuth: true,
  },

  // Cirurgias Ginecológicas
  {
    code: "30701016",
    description: "Histerectomia total abdominal",
    chapter: "3",
    group: "Ginecologia",
    porte: "9",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30701024",
    description: "Histerectomia total vaginal",
    chapter: "3",
    group: "Ginecologia",
    porte: "9",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30701032",
    description: "Histerectomia laparoscópica",
    chapter: "3",
    group: "Ginecologia",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30701040",
    description: "Miomectomia",
    chapter: "3",
    group: "Ginecologia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30701059",
    description: "Ooforectomia unilateral",
    chapter: "3",
    group: "Ginecologia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30701067",
    description: "Ooforectomia bilateral",
    chapter: "3",
    group: "Ginecologia",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30701075",
    description: "Salpingectomia unilateral",
    chapter: "3",
    group: "Ginecologia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30701083",
    description: "Salpingectomia bilateral (laqueadura)",
    chapter: "3",
    group: "Ginecologia",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30701091",
    description: "Conização do colo uterino",
    chapter: "3",
    group: "Ginecologia",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30701105",
    description: "Curetagem uterina",
    chapter: "3",
    group: "Ginecologia",
    porte: "3",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30701113",
    description: "Histeroscopia cirúrgica",
    chapter: "3",
    group: "Ginecologia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30701121",
    description: "Perineoplastia",
    chapter: "3",
    group: "Ginecologia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30701130",
    description: "Colpoperineoplastia anterior e posterior",
    chapter: "3",
    group: "Ginecologia",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30701148",
    description: "Correção de incontinência urinária (sling)",
    chapter: "3",
    group: "Ginecologia",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30701156",
    description: "Mastectomia radical",
    chapter: "3",
    group: "Ginecologia",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30701164",
    description: "Mastectomia simples",
    chapter: "3",
    group: "Ginecologia",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30701172",
    description: "Quadrantectomia",
    chapter: "3",
    group: "Ginecologia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30701180",
    description: "Nodulectomia mamária",
    chapter: "3",
    group: "Ginecologia",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30701199",
    description: "Mamoplastia redutora bilateral",
    chapter: "3",
    group: "Ginecologia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30701202",
    description: "Reconstrução mamária com prótese",
    chapter: "3",
    group: "Ginecologia",
    porte: "9",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30701210",
    description: "Reconstrução mamária com retalho TRAM",
    chapter: "3",
    group: "Ginecologia",
    porte: "13",
    porteAnestesico: "6",
    requiresAuth: true,
  },

  // Cirurgias Ortopédicas
  {
    code: "30801012",
    description: "Artroplastia total de quadril",
    chapter: "3",
    group: "Ortopedia",
    porte: "11",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30801020",
    description: "Artroplastia total de joelho",
    chapter: "3",
    group: "Ortopedia",
    porte: "11",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30801039",
    description: "Artroplastia parcial de quadril",
    chapter: "3",
    group: "Ortopedia",
    porte: "9",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30801047",
    description: "Artroscopia de joelho diagnóstica",
    chapter: "3",
    group: "Ortopedia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30801055",
    description: "Artroscopia de joelho - meniscectomia",
    chapter: "3",
    group: "Ortopedia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30801063",
    description: "Artroscopia de joelho - reconstrução de LCA",
    chapter: "3",
    group: "Ortopedia",
    porte: "9",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30801071",
    description: "Artroscopia de ombro diagnóstica",
    chapter: "3",
    group: "Ortopedia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30801080",
    description: "Artroscopia de ombro - reparo do manguito rotador",
    chapter: "3",
    group: "Ortopedia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30801098",
    description: "Osteossíntese de fêmur proximal (colo)",
    chapter: "3",
    group: "Ortopedia",
    porte: "9",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30801101",
    description: "Osteossíntese de fêmur diáfise",
    chapter: "3",
    group: "Ortopedia",
    porte: "9",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30801110",
    description: "Osteossíntese de tíbia",
    chapter: "3",
    group: "Ortopedia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30801128",
    description: "Osteossíntese de úmero proximal",
    chapter: "3",
    group: "Ortopedia",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30801136",
    description: "Osteossíntese de rádio distal",
    chapter: "3",
    group: "Ortopedia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30801144",
    description: "Osteossíntese de tornozelo",
    chapter: "3",
    group: "Ortopedia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30801152",
    description: "Osteossíntese de clavícula",
    chapter: "3",
    group: "Ortopedia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30801160",
    description: "Redução incruenta de fratura",
    chapter: "3",
    group: "Ortopedia",
    porte: "3",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30801179",
    description: "Redução cruenta de luxação",
    chapter: "3",
    group: "Ortopedia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30801187",
    description: "Tratamento cirúrgico de síndrome do túnel do carpo",
    chapter: "3",
    group: "Ortopedia",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30801195",
    description: "Tratamento cirúrgico de dedo em gatilho",
    chapter: "3",
    group: "Ortopedia",
    porte: "3",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30801209",
    description: "Fasciotomia palmar (Dupuytren)",
    chapter: "3",
    group: "Ortopedia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30801217",
    description: "Correção de hallux valgus",
    chapter: "3",
    group: "Ortopedia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30801225",
    description: "Artrodese de coluna lombar (por segmento)",
    chapter: "3",
    group: "Ortopedia",
    porte: "12",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "30801233",
    description: "Discectomia lombar percutânea",
    chapter: "3",
    group: "Ortopedia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30801241",
    description: "Correção de escoliose",
    chapter: "3",
    group: "Ortopedia",
    porte: "14",
    porteAnestesico: "7",
    requiresAuth: true,
  },
  {
    code: "30801250",
    description: "Retirada de material de síntese",
    chapter: "3",
    group: "Ortopedia",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },

  // Cirurgias Oftalmológicas
  {
    code: "30901010",
    description: "Facoemulsificação com implante de LIO",
    chapter: "3",
    group: "Oftalmologia",
    porte: "7",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30901029",
    description: "Extração extracapsular de catarata",
    chapter: "3",
    group: "Oftalmologia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30901037",
    description: "Vitrectomia posterior",
    chapter: "3",
    group: "Oftalmologia",
    porte: "10",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30901045",
    description: "Trabeculectomia",
    chapter: "3",
    group: "Oftalmologia",
    porte: "7",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30901053",
    description: "Implante de válvula para glaucoma",
    chapter: "3",
    group: "Oftalmologia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30901061",
    description: "Cirurgia de descolamento de retina",
    chapter: "3",
    group: "Oftalmologia",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "30901070",
    description: "Cirurgia refrativa - LASIK",
    chapter: "3",
    group: "Oftalmologia",
    porte: "5",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30901088",
    description: "Cirurgia refrativa - PRK",
    chapter: "3",
    group: "Oftalmologia",
    porte: "5",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30901096",
    description: "Transplante de córnea",
    chapter: "3",
    group: "Oftalmologia",
    porte: "9",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30901100",
    description: "Pterígio - exérese",
    chapter: "3",
    group: "Oftalmologia",
    porte: "3",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30901118",
    description: "Correção de estrabismo - um músculo",
    chapter: "3",
    group: "Oftalmologia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "30901126",
    description: "Correção de estrabismo - dois ou mais músculos",
    chapter: "3",
    group: "Oftalmologia",
    porte: "7",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30901134",
    description: "Blefaroplastia superior bilateral",
    chapter: "3",
    group: "Oftalmologia",
    porte: "5",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30901142",
    description: "Blefaroplastia inferior bilateral",
    chapter: "3",
    group: "Oftalmologia",
    porte: "5",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30901150",
    description: "Correção de ptose palpebral",
    chapter: "3",
    group: "Oftalmologia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30901169",
    description: "Correção de entrópio ou ectrópio",
    chapter: "3",
    group: "Oftalmologia",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "30901177",
    description: "Dacriocistorrinostomia",
    chapter: "3",
    group: "Oftalmologia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30901185",
    description: "Enucleação do globo ocular",
    chapter: "3",
    group: "Oftalmologia",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "30901193",
    description: "Implante de prótese ocular",
    chapter: "3",
    group: "Oftalmologia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "30901207",
    description: "Injeção intravítrea",
    chapter: "3",
    group: "Oftalmologia",
    porte: "3",
    porteAnestesico: "1",
    requiresAuth: false,
  },

  // Cirurgias Otorrinolaringológicas
  {
    code: "31001014",
    description: "Adenoidectomia",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "31001022",
    description: "Amigdalectomia",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "4",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "31001030",
    description: "Adenoamigdalectomia",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "31001049",
    description: "Septoplastia",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "5",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "31001057",
    description: "Turbinectomia",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "31001065",
    description: "Sinusectomia maxilar (Caldwell-Luc)",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "31001073",
    description: "Cirurgia endoscópica nasossinusal (CENS)",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "31001081",
    description: "Polipectomia nasal",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "4",
    porteAnestesico: "2",
    requiresAuth: false,
  },
  {
    code: "31001090",
    description: "Timpanoplastia",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "31001103",
    description: "Mastoidectomia",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "9",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "31001111",
    description: "Estapedectomia/estapedotomia",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "31001120",
    description: "Implante coclear",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "12",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "31001138",
    description: "Laringectomia total",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "12",
    porteAnestesico: "6",
    requiresAuth: true,
  },
  {
    code: "31001146",
    description: "Laringectomia parcial",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "31001154",
    description: "Microcirurgia de laringe",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "31001162",
    description: "Traqueostomia",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "4",
    porteAnestesico: "3",
    requiresAuth: false,
  },
  {
    code: "31001170",
    description: "Parotidectomia total",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "10",
    porteAnestesico: "5",
    requiresAuth: true,
  },
  {
    code: "31001189",
    description: "Parotidectomia parcial",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "31001197",
    description: "Tireoidectomia total",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "31001200",
    description: "Tireoidectomia parcial (lobectomia)",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: false,
  },
  {
    code: "31001219",
    description: "Paratireoidectomia",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "8",
    porteAnestesico: "4",
    requiresAuth: true,
  },
  {
    code: "31001227",
    description: "Uvulopalatofaringoplastia (UPFP)",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "6",
    porteAnestesico: "3",
    requiresAuth: true,
  },
  {
    code: "31001235",
    description: "Rinoplastia funcional",
    chapter: "3",
    group: "Otorrinolaringologia",
    porte: "7",
    porteAnestesico: "4",
    requiresAuth: true,
  },
]

// Capítulo 4 - Exames e Procedimentos Diagnósticos
const CAPITULO_4_EXAMES: TUSSProcedure[] = [
  // Patologia Clínica - Hematologia
  { code: "40301010", description: "Hemograma completo", chapter: "4", group: "Hematologia", requiresAuth: false },
  { code: "40301028", description: "Contagem de plaquetas", chapter: "4", group: "Hematologia", requiresAuth: false },
  {
    code: "40301036",
    description: "Contagem de reticulócitos",
    chapter: "4",
    group: "Hematologia",
    requiresAuth: false,
  },
  {
    code: "40301044",
    description: "Velocidade de hemossedimentação (VHS)",
    chapter: "4",
    group: "Hematologia",
    requiresAuth: false,
  },
  {
    code: "40301052",
    description: "Tempo de protrombina (TP/INR)",
    chapter: "4",
    group: "Hematologia",
    requiresAuth: false,
  },
  {
    code: "40301060",
    description: "Tempo de tromboplastina parcial ativada (TTPA)",
    chapter: "4",
    group: "Hematologia",
    requiresAuth: false,
  },
  { code: "40301079", description: "Fibrinogênio", chapter: "4", group: "Hematologia", requiresAuth: false },
  { code: "40301087", description: "D-dímero", chapter: "4", group: "Hematologia", requiresAuth: false },
  {
    code: "40301095",
    description: "Eletroforese de hemoglobina",
    chapter: "4",
    group: "Hematologia",
    requiresAuth: false,
  },
  { code: "40301109", description: "Teste de Coombs direto", chapter: "4", group: "Hematologia", requiresAuth: false },
  {
    code: "40301117",
    description: "Teste de Coombs indireto",
    chapter: "4",
    group: "Hematologia",
    requiresAuth: false,
  },
  {
    code: "40301125",
    description: "Tipagem sanguínea ABO/Rh",
    chapter: "4",
    group: "Hematologia",
    requiresAuth: false,
  },
  {
    code: "40301133",
    description: "Pesquisa de células falciformes",
    chapter: "4",
    group: "Hematologia",
    requiresAuth: false,
  },
  { code: "40301141", description: "Mielograma", chapter: "4", group: "Hematologia", requiresAuth: true },
  { code: "40301150", description: "Biópsia de medula óssea", chapter: "4", group: "Hematologia", requiresAuth: true },

  // Patologia Clínica - Bioquímica
  { code: "40302016", description: "Glicose", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302024", description: "Glicose pós-prandial", chapter: "4", group: "Bioquímica", requiresAuth: false },
  {
    code: "40302032",
    description: "Hemoglobina glicada (HbA1c)",
    chapter: "4",
    group: "Bioquímica",
    requiresAuth: false,
  },
  {
    code: "40302040",
    description: "Teste de tolerância à glicose (TOTG)",
    chapter: "4",
    group: "Bioquímica",
    requiresAuth: false,
  },
  { code: "40302059", description: "Ureia", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302067", description: "Creatinina", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302075", description: "Ácido úrico", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302083", description: "Sódio", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302091", description: "Potássio", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302105", description: "Cloreto", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302113", description: "Cálcio total", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302121", description: "Cálcio iônico", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302130", description: "Fósforo", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302148", description: "Magnésio", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302156", description: "Ferro sérico", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302164", description: "Ferritina", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302172", description: "Transferrina", chapter: "4", group: "Bioquímica", requiresAuth: false },
  {
    code: "40302180",
    description: "Capacidade de ligação do ferro (TIBC)",
    chapter: "4",
    group: "Bioquímica",
    requiresAuth: false,
  },
  {
    code: "40302199",
    description: "Bilirrubinas totais e frações",
    chapter: "4",
    group: "Bioquímica",
    requiresAuth: false,
  },
  { code: "40302202", description: "TGO (AST)", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302210", description: "TGP (ALT)", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302229", description: "Gama-GT (GGT)", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302237", description: "Fosfatase alcalina", chapter: "4", group: "Bioquímica", requiresAuth: false },
  {
    code: "40302245",
    description: "LDH (desidrogenase láctica)",
    chapter: "4",
    group: "Bioquímica",
    requiresAuth: false,
  },
  { code: "40302253", description: "CPK (creatinoquinase)", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302261", description: "CPK-MB", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302270", description: "Troponina I ou T", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302288", description: "Proteína C reativa (PCR)", chapter: "4", group: "Bioquímica", requiresAuth: false },
  {
    code: "40302296",
    description: "Proteína C reativa ultrassensível",
    chapter: "4",
    group: "Bioquímica",
    requiresAuth: false,
  },
  {
    code: "40302300",
    description: "Proteínas totais e frações",
    chapter: "4",
    group: "Bioquímica",
    requiresAuth: false,
  },
  { code: "40302318", description: "Albumina", chapter: "4", group: "Bioquímica", requiresAuth: false },
  {
    code: "40302326",
    description: "Eletroforese de proteínas",
    chapter: "4",
    group: "Bioquímica",
    requiresAuth: false,
  },
  { code: "40302334", description: "Amilase", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302342", description: "Lipase", chapter: "4", group: "Bioquímica", requiresAuth: false },

  // Perfil Lipídico
  { code: "40302350", description: "Colesterol total", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302369", description: "Colesterol HDL", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302377", description: "Colesterol LDL", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302385", description: "Colesterol VLDL", chapter: "4", group: "Bioquímica", requiresAuth: false },
  { code: "40302393", description: "Triglicerídeos", chapter: "4", group: "Bioquímica", requiresAuth: false },

  // Hormônios
  { code: "40303012", description: "TSH", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303020", description: "T4 livre", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303039", description: "T4 total", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303047", description: "T3 livre", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303055", description: "T3 total", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303063", description: "Anti-TPO", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303071", description: "Anti-tireoglobulina", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303080", description: "Tireoglobulina", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303098", description: "FSH", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303101", description: "LH", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303110", description: "Estradiol", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303128", description: "Progesterona", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303136", description: "Prolactina", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303144", description: "Testosterona total", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303152", description: "Testosterona livre", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303160", description: "DHEA-S", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303179", description: "Cortisol", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303187", description: "ACTH", chapter: "4", group: "Hormônios", requiresAuth: false },
  {
    code: "40303195",
    description: "GH (hormônio do crescimento)",
    chapter: "4",
    group: "Hormônios",
    requiresAuth: false,
  },
  { code: "40303209", description: "IGF-1 (somatomedina C)", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303217", description: "PTH (paratormônio)", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303225", description: "Vitamina D (25-OH)", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303233", description: "Insulina basal", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303241", description: "Peptídeo C", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303250", description: "Beta-HCG quantitativo", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303268", description: "PSA total", chapter: "4", group: "Hormônios", requiresAuth: false },
  { code: "40303276", description: "PSA livre", chapter: "4", group: "Hormônios", requiresAuth: false },

  // Marcadores Tumorais
  {
    code: "40304019",
    description: "AFP (alfa-fetoproteína)",
    chapter: "4",
    group: "Marcadores Tumorais",
    requiresAuth: false,
  },
  {
    code: "40304027",
    description: "CEA (antígeno carcinoembriogênico)",
    chapter: "4",
    group: "Marcadores Tumorais",
    requiresAuth: false,
  },
  { code: "40304035", description: "CA 125", chapter: "4", group: "Marcadores Tumorais", requiresAuth: false },
  { code: "40304043", description: "CA 19-9", chapter: "4", group: "Marcadores Tumorais", requiresAuth: false },
  { code: "40304051", description: "CA 15-3", chapter: "4", group: "Marcadores Tumorais", requiresAuth: false },
  { code: "40304060", description: "CA 72-4", chapter: "4", group: "Marcadores Tumorais", requiresAuth: false },
  { code: "40304078", description: "Calcitonina", chapter: "4", group: "Marcadores Tumorais", requiresAuth: false },
  { code: "40304086", description: "Cromogranina A", chapter: "4", group: "Marcadores Tumorais", requiresAuth: false },

  // Urinálise
  { code: "40305015", description: "Urina tipo I (EAS)", chapter: "4", group: "Urinálise", requiresAuth: false },
  {
    code: "40305023",
    description: "Urina de 24 horas - proteínas",
    chapter: "4",
    group: "Urinálise",
    requiresAuth: false,
  },
  {
    code: "40305031",
    description: "Urina de 24 horas - creatinina",
    chapter: "4",
    group: "Urinálise",
    requiresAuth: false,
  },
  { code: "40305040", description: "Clearance de creatinina", chapter: "4", group: "Urinálise", requiresAuth: false },
  { code: "40305058", description: "Microalbuminúria", chapter: "4", group: "Urinálise", requiresAuth: false },
  {
    code: "40305066",
    description: "Urocultura com antibiograma",
    chapter: "4",
    group: "Urinálise",
    requiresAuth: false,
  },
  {
    code: "40305074",
    description: "Pesquisa de dismorfismo eritrocitário",
    chapter: "4",
    group: "Urinálise",
    requiresAuth: false,
  },

  // Parasitológico e Fezes
  { code: "40306011", description: "Parasitológico de fezes", chapter: "4", group: "Fezes", requiresAuth: false },
  { code: "40306020", description: "Sangue oculto nas fezes", chapter: "4", group: "Fezes", requiresAuth: false },
  { code: "40306038", description: "Coprocultura", chapter: "4", group: "Fezes", requiresAuth: false },
  { code: "40306046", description: "Pesquisa de gordura fecal", chapter: "4", group: "Fezes", requiresAuth: false },
  { code: "40306054", description: "Calprotectina fecal", chapter: "4", group: "Fezes", requiresAuth: false },

  // Sorologias
  { code: "40307018", description: "Anti-HIV 1 e 2", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307026", description: "VDRL", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307034", description: "FTA-Abs", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307042", description: "Hepatite A - anti-HAV IgM", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307050", description: "Hepatite A - anti-HAV IgG", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307069", description: "Hepatite B - HBsAg", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307077", description: "Hepatite B - anti-HBs", chapter: "4", group: "Sorologia", requiresAuth: false },
  {
    code: "40307085",
    description: "Hepatite B - anti-HBc total",
    chapter: "4",
    group: "Sorologia",
    requiresAuth: false,
  },
  { code: "40307093", description: "Hepatite B - anti-HBc IgM", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307107", description: "Hepatite B - HBeAg", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307115", description: "Hepatite B - anti-HBe", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307123", description: "Hepatite C - anti-HCV", chapter: "4", group: "Sorologia", requiresAuth: false },
  {
    code: "40307131",
    description: "Hepatite C - HCV RNA (PCR qualitativo)",
    chapter: "4",
    group: "Sorologia",
    requiresAuth: true,
  },
  {
    code: "40307140",
    description: "Hepatite C - HCV RNA (PCR quantitativo)",
    chapter: "4",
    group: "Sorologia",
    requiresAuth: true,
  },
  { code: "40307158", description: "Hepatite C - genotipagem", chapter: "4", group: "Sorologia", requiresAuth: true },
  { code: "40307166", description: "Rubéola - IgM", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307174", description: "Rubéola - IgG", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307182", description: "Toxoplasmose - IgM", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307190", description: "Toxoplasmose - IgG", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307204", description: "Citomegalovírus - IgM", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307212", description: "Citomegalovírus - IgG", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307220", description: "Mononucleose - monoteste", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307239", description: "Epstein-Barr - VCA IgM", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307247", description: "Epstein-Barr - VCA IgG", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307255", description: "Herpes simples - IgM", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307263", description: "Herpes simples - IgG", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307271", description: "Dengue - NS1", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307280", description: "Dengue - IgM", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307298", description: "Dengue - IgG", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307301", description: "Zika vírus - IgM", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307310", description: "Chikungunya - IgM", chapter: "4", group: "Sorologia", requiresAuth: false },
  { code: "40307328", description: "COVID-19 - RT-PCR", chapter: "4", group: "Sorologia", requiresAuth: false },
  {
    code: "40307336",
    description: "COVID-19 - Anticorpos IgG/IgM",
    chapter: "4",
    group: "Sorologia",
    requiresAuth: false,
  },

  // Autoimunidade
  {
    code: "40308014",
    description: "FAN (fator antinuclear)",
    chapter: "4",
    group: "Autoimunidade",
    requiresAuth: false,
  },
  { code: "40308022", description: "Anti-DNA nativo", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  { code: "40308030", description: "Anti-Sm", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  { code: "40308049", description: "Anti-RNP", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  { code: "40308057", description: "Anti-SSA (Ro)", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  { code: "40308065", description: "Anti-SSB (La)", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  { code: "40308073", description: "Anti-Jo1", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  { code: "40308081", description: "Anti-Scl70", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  { code: "40308090", description: "Fator reumatoide", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  { code: "40308103", description: "Anti-CCP", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  {
    code: "40308111",
    description: "ANCA (c-ANCA e p-ANCA)",
    chapter: "4",
    group: "Autoimunidade",
    requiresAuth: false,
  },
  { code: "40308120", description: "Complemento C3", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  { code: "40308138", description: "Complemento C4", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  { code: "40308146", description: "CH50", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  { code: "40308154", description: "Crioglobulinas", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  {
    code: "40308162",
    description: "Anticardiolipina IgG e IgM",
    chapter: "4",
    group: "Autoimunidade",
    requiresAuth: false,
  },
  { code: "40308170", description: "Anticoagulante lúpico", chapter: "4", group: "Autoimunidade", requiresAuth: false },
  {
    code: "40308189",
    description: "Anti-beta2 glicoproteína I",
    chapter: "4",
    group: "Autoimunidade",
    requiresAuth: false,
  },

  // Imagens - Radiologia Convencional
  {
    code: "40401014",
    description: "Radiografia de tórax (PA)",
    chapter: "4",
    group: "Radiologia",
    requiresAuth: false,
  },
  {
    code: "40401022",
    description: "Radiografia de tórax (PA e perfil)",
    chapter: "4",
    group: "Radiologia",
    requiresAuth: false,
  },
  { code: "40401030", description: "Radiografia de crânio", chapter: "4", group: "Radiologia", requiresAuth: false },
  {
    code: "40401049",
    description: "Radiografia de seios da face",
    chapter: "4",
    group: "Radiologia",
    requiresAuth: false,
  },
  {
    code: "40401057",
    description: "Radiografia de coluna cervical",
    chapter: "4",
    group: "Radiologia",
    requiresAuth: false,
  },
  {
    code: "40401065",
    description: "Radiografia de coluna torácica",
    chapter: "4",
    group: "Radiologia",
    requiresAuth: false,
  },
  {
    code: "40401073",
    description: "Radiografia de coluna lombossacra",
    chapter: "4",
    group: "Radiologia",
    requiresAuth: false,
  },
  {
    code: "40401081",
    description: "Radiografia de abdome (simples)",
    chapter: "4",
    group: "Radiologia",
    requiresAuth: false,
  },
  { code: "40401090", description: "Radiografia de mão", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401103", description: "Radiografia de punho", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401111", description: "Radiografia de antebraço", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401120", description: "Radiografia de cotovelo", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401138", description: "Radiografia de úmero", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401146", description: "Radiografia de ombro", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401154", description: "Radiografia de clavícula", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401162", description: "Radiografia de bacia", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401170", description: "Radiografia de quadril", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401189", description: "Radiografia de fêmur", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401197", description: "Radiografia de joelho", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401200", description: "Radiografia de perna", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401219", description: "Radiografia de tornozelo", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401227", description: "Radiografia de pé", chapter: "4", group: "Radiologia", requiresAuth: false },
  { code: "40401235", description: "Radiografia de calcâneo", chapter: "4", group: "Radiologia", requiresAuth: false },

  // Tomografia Computadorizada
  { code: "40501019", description: "Tomografia de crânio", chapter: "4", group: "Tomografia", requiresAuth: true },
  {
    code: "40501027",
    description: "Tomografia de crânio com contraste",
    chapter: "4",
    group: "Tomografia",
    requiresAuth: true,
  },
  { code: "40501035", description: "Tomografia de órbitas", chapter: "4", group: "Tomografia", requiresAuth: true },
  {
    code: "40501043",
    description: "Tomografia de seios da face",
    chapter: "4",
    group: "Tomografia",
    requiresAuth: true,
  },
  { code: "40501051", description: "Tomografia de pescoço", chapter: "4", group: "Tomografia", requiresAuth: true },
  { code: "40501060", description: "Tomografia de tórax", chapter: "4", group: "Tomografia", requiresAuth: true },
  {
    code: "40501078",
    description: "Tomografia de tórax com contraste",
    chapter: "4",
    group: "Tomografia",
    requiresAuth: true,
  },
  { code: "40501086", description: "Angiotomografia de tórax", chapter: "4", group: "Tomografia", requiresAuth: true },
  {
    code: "40501094",
    description: "Tomografia de abdome total",
    chapter: "4",
    group: "Tomografia",
    requiresAuth: true,
  },
  {
    code: "40501108",
    description: "Tomografia de abdome superior",
    chapter: "4",
    group: "Tomografia",
    requiresAuth: true,
  },
  { code: "40501116", description: "Tomografia de pelve", chapter: "4", group: "Tomografia", requiresAuth: true },
  { code: "40501124", description: "Angiomtomografia de aorta", chapter: "4", group: "Tomografia", requiresAuth: true },
  {
    code: "40501132",
    description: "Tomografia de coluna cervical",
    chapter: "4",
    group: "Tomografia",
    requiresAuth: true,
  },
  {
    code: "40501140",
    description: "Tomografia de coluna torácica",
    chapter: "4",
    group: "Tomografia",
    requiresAuth: true,
  },
  {
    code: "40501159",
    description: "Tomografia de coluna lombar",
    chapter: "4",
    group: "Tomografia",
    requiresAuth: true,
  },
  {
    code: "40501167",
    description: "Tomografia de articulação (membro superior)",
    chapter: "4",
    group: "Tomografia",
    requiresAuth: true,
  },
  {
    code: "40501175",
    description: "Tomografia de articulação (membro inferior)",
    chapter: "4",
    group: "Tomografia",
    requiresAuth: true,
  },
  {
    code: "40501183",
    description: "Angiotomografia coronariana",
    chapter: "4",
    group: "Tomografia",
    requiresAuth: true,
  },
  {
    code: "40501191",
    description: "Escore de cálcio coronariano",
    chapter: "4",
    group: "Tomografia",
    requiresAuth: true,
  },

  // Ressonância Magnética
  { code: "40601013", description: "Ressonância de crânio", chapter: "4", group: "Ressonância", requiresAuth: true },
  {
    code: "40601021",
    description: "Ressonância de crânio com contraste",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  {
    code: "40601030",
    description: "Ressonância de sela túrcica (hipófise)",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  {
    code: "40601048",
    description: "Angiorressonância cerebral",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  { code: "40601056", description: "Ressonância de órbitas", chapter: "4", group: "Ressonância", requiresAuth: true },
  { code: "40601064", description: "Ressonância de pescoço", chapter: "4", group: "Ressonância", requiresAuth: true },
  {
    code: "40601072",
    description: "Ressonância de coluna cervical",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  {
    code: "40601080",
    description: "Ressonância de coluna torácica",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  {
    code: "40601099",
    description: "Ressonância de coluna lombossacra",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  {
    code: "40601102",
    description: "Ressonância de plexo braquial",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  { code: "40601110", description: "Ressonância de tórax", chapter: "4", group: "Ressonância", requiresAuth: true },
  { code: "40601129", description: "Ressonância cardíaca", chapter: "4", group: "Ressonância", requiresAuth: true },
  {
    code: "40601137",
    description: "Ressonância de abdome superior",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  {
    code: "40601145",
    description: "Ressonância de pelve masculina",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  {
    code: "40601153",
    description: "Ressonância de pelve feminina",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  {
    code: "40601161",
    description: "Ressonância de próstata multiparamétrica",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  { code: "40601170", description: "Ressonância de ombro", chapter: "4", group: "Ressonância", requiresAuth: true },
  { code: "40601188", description: "Ressonância de cotovelo", chapter: "4", group: "Ressonância", requiresAuth: true },
  { code: "40601196", description: "Ressonância de punho", chapter: "4", group: "Ressonância", requiresAuth: true },
  { code: "40601200", description: "Ressonância de mão", chapter: "4", group: "Ressonância", requiresAuth: true },
  { code: "40601218", description: "Ressonância de quadril", chapter: "4", group: "Ressonância", requiresAuth: true },
  { code: "40601226", description: "Ressonância de joelho", chapter: "4", group: "Ressonância", requiresAuth: true },
  { code: "40601234", description: "Ressonância de tornozelo", chapter: "4", group: "Ressonância", requiresAuth: true },
  { code: "40601242", description: "Ressonância de pé", chapter: "4", group: "Ressonância", requiresAuth: true },
  {
    code: "40601250",
    description: "Ressonância de mama bilateral",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  { code: "40601269", description: "Colangiorresonância", chapter: "4", group: "Ressonância", requiresAuth: true },
  {
    code: "40601277",
    description: "Angiorressonância de aorta",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  {
    code: "40601285",
    description: "Angiorressonância de membros inferiores",
    chapter: "4",
    group: "Ressonância",
    requiresAuth: true,
  },
  { code: "40601293", description: "Ressonância fetal", chapter: "4", group: "Ressonância", requiresAuth: true },

  // Ultrassonografia
  {
    code: "40701018",
    description: "Ultrassonografia de abdome total",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701026",
    description: "Ultrassonografia de abdome superior",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701034",
    description: "Ultrassonografia de fígado e vias biliares",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701042",
    description: "Ultrassonografia de rins e vias urinárias",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701050",
    description: "Ultrassonografia de próstata (abdominal)",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701069",
    description: "Ultrassonografia de próstata (transretal)",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701077",
    description: "Ultrassonografia de tireoide",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701085",
    description: "Ultrassonografia de mamas",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701093",
    description: "Ultrassonografia de bolsa escrotal",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701107",
    description: "Ultrassonografia pélvica feminina (transabdominal)",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701115",
    description: "Ultrassonografia pélvica feminina (transvaginal)",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701123",
    description: "Ultrassonografia obstétrica (1º trimestre)",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701131",
    description: "Ultrassonografia obstétrica (2º/3º trimestre)",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701140",
    description: "Ultrassonografia obstétrica morfológica",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701158",
    description: "Ultrassonografia obstétrica com Doppler",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701166",
    description: "Ultrassonografia transfontanela",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701174",
    description: "Ultrassonografia de partes moles",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701182",
    description: "Ultrassonografia de articulação",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701190",
    description: "Ultrassonografia de ombro",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },
  {
    code: "40701204",
    description: "Ultrassonografia de quadril infantil",
    chapter: "4",
    group: "Ultrassonografia",
    requiresAuth: false,
  },

  // Doppler Vascular
  {
    code: "40801012",
    description: "Doppler colorido de carótidas e vertebrais",
    chapter: "4",
    group: "Doppler",
    requiresAuth: false,
  },
  {
    code: "40801020",
    description: "Doppler colorido de aorta e ilíacas",
    chapter: "4",
    group: "Doppler",
    requiresAuth: false,
  },
  {
    code: "40801039",
    description: "Doppler colorido de artérias renais",
    chapter: "4",
    group: "Doppler",
    requiresAuth: false,
  },
  {
    code: "40801047",
    description: "Doppler colorido de artérias de membros inferiores",
    chapter: "4",
    group: "Doppler",
    requiresAuth: false,
  },
  {
    code: "40801055",
    description: "Doppler colorido de artérias de membros superiores",
    chapter: "4",
    group: "Doppler",
    requiresAuth: false,
  },
  {
    code: "40801063",
    description: "Doppler colorido de veias de membros inferiores",
    chapter: "4",
    group: "Doppler",
    requiresAuth: false,
  },
  {
    code: "40801071",
    description: "Doppler colorido de veias de membros superiores",
    chapter: "4",
    group: "Doppler",
    requiresAuth: false,
  },
  {
    code: "40801080",
    description: "Doppler colorido de veia porta e hepáticas",
    chapter: "4",
    group: "Doppler",
    requiresAuth: false,
  },
  { code: "40801098", description: "Doppler transcraniano", chapter: "4", group: "Doppler", requiresAuth: true },

  // Mamografia
  { code: "40901015", description: "Mamografia bilateral", chapter: "4", group: "Mamografia", requiresAuth: false },
  { code: "40901023", description: "Mamografia unilateral", chapter: "4", group: "Mamografia", requiresAuth: false },
  {
    code: "40901031",
    description: "Mamografia digital com tomossíntese",
    chapter: "4",
    group: "Mamografia",
    requiresAuth: false,
  },
  {
    code: "40901040",
    description: "Densitometria óssea (coluna e fêmur)",
    chapter: "4",
    group: "Densitometria",
    requiresAuth: false,
  },
  {
    code: "40901058",
    description: "Densitometria óssea de corpo inteiro",
    chapter: "4",
    group: "Densitometria",
    requiresAuth: false,
  },

  // Cardiologia
  { code: "41001010", description: "Eletrocardiograma", chapter: "4", group: "Cardiologia", requiresAuth: false },
  { code: "41001028", description: "Teste ergométrico", chapter: "4", group: "Cardiologia", requiresAuth: false },
  { code: "41001036", description: "Holter 24 horas", chapter: "4", group: "Cardiologia", requiresAuth: false },
  { code: "41001044", description: "MAPA 24 horas", chapter: "4", group: "Cardiologia", requiresAuth: false },
  {
    code: "41001052",
    description: "Ecocardiograma transtorácico",
    chapter: "4",
    group: "Cardiologia",
    requiresAuth: false,
  },
  {
    code: "41001060",
    description: "Ecocardiograma transesofágico",
    chapter: "4",
    group: "Cardiologia",
    requiresAuth: true,
  },
  {
    code: "41001079",
    description: "Ecocardiograma de estresse",
    chapter: "4",
    group: "Cardiologia",
    requiresAuth: true,
  },
  { code: "41001087", description: "Ecocardiograma fetal", chapter: "4", group: "Cardiologia", requiresAuth: false },
  {
    code: "41001095",
    description: "Cateterismo cardíaco diagnóstico",
    chapter: "4",
    group: "Cardiologia",
    requiresAuth: true,
  },
  {
    code: "41001109",
    description: "Angioplastia coronariana com stent",
    chapter: "4",
    group: "Cardiologia",
    requiresAuth: true,
  },
  { code: "41001117", description: "Estudo eletrofisiológico", chapter: "4", group: "Cardiologia", requiresAuth: true },
  {
    code: "41001125",
    description: "Ablação por radiofrequência",
    chapter: "4",
    group: "Cardiologia",
    requiresAuth: true,
  },
  {
    code: "41001133",
    description: "Cintilografia de perfusão miocárdica",
    chapter: "4",
    group: "Cardiologia",
    requiresAuth: true,
  },

  // Neurologia
  { code: "41101012", description: "Eletroencefalograma", chapter: "4", group: "Neurologia", requiresAuth: false },
  {
    code: "41101020",
    description: "Eletroencefalograma com mapeamento",
    chapter: "4",
    group: "Neurologia",
    requiresAuth: false,
  },
  { code: "41101039", description: "Vídeo-eletroencefalograma", chapter: "4", group: "Neurologia", requiresAuth: true },
  { code: "41101047", description: "Eletroneuromiografia", chapter: "4", group: "Neurologia", requiresAuth: false },
  { code: "41101055", description: "Potencial evocado visual", chapter: "4", group: "Neurologia", requiresAuth: false },
  {
    code: "41101063",
    description: "Potencial evocado auditivo",
    chapter: "4",
    group: "Neurologia",
    requiresAuth: false,
  },
  {
    code: "41101071",
    description: "Potencial evocado somatossensitivo",
    chapter: "4",
    group: "Neurologia",
    requiresAuth: false,
  },
  { code: "41101080", description: "Polissonografia", chapter: "4", group: "Neurologia", requiresAuth: true },

  // Gastroenterologia
  {
    code: "41201019",
    description: "Endoscopia digestiva alta",
    chapter: "4",
    group: "Gastroenterologia",
    requiresAuth: false,
  },
  { code: "41201027", description: "Colonoscopia", chapter: "4", group: "Gastroenterologia", requiresAuth: true },
  {
    code: "41201035",
    description: "Retossigmoidoscopia",
    chapter: "4",
    group: "Gastroenterologia",
    requiresAuth: false,
  },
  {
    code: "41201043",
    description: "Colangiopancreatografia retrógrada (CPRE)",
    chapter: "4",
    group: "Gastroenterologia",
    requiresAuth: true,
  },
  { code: "41201051", description: "Ecoendoscopia", chapter: "4", group: "Gastroenterologia", requiresAuth: true },
  {
    code: "41201060",
    description: "Cápsula endoscópica",
    chapter: "4",
    group: "Gastroenterologia",
    requiresAuth: true,
  },
  {
    code: "41201078",
    description: "pHmetria esofágica 24 horas",
    chapter: "4",
    group: "Gastroenterologia",
    requiresAuth: true,
  },
  {
    code: "41201086",
    description: "Manometria esofágica",
    chapter: "4",
    group: "Gastroenterologia",
    requiresAuth: true,
  },
  {
    code: "41201094",
    description: "Manometria anorretal",
    chapter: "4",
    group: "Gastroenterologia",
    requiresAuth: true,
  },
  {
    code: "41201108",
    description: "Teste respiratório para H. pylori",
    chapter: "4",
    group: "Gastroenterologia",
    requiresAuth: false,
  },
  {
    code: "41201116",
    description: "Teste respiratório de hidrogênio",
    chapter: "4",
    group: "Gastroenterologia",
    requiresAuth: false,
  },
  {
    code: "41201124",
    description: "Elastografia hepática (Fibroscan)",
    chapter: "4",
    group: "Gastroenterologia",
    requiresAuth: true,
  },

  // Pneumologia
  { code: "41301016", description: "Espirometria", chapter: "4", group: "Pneumologia", requiresAuth: false },
  {
    code: "41301024",
    description: "Espirometria com prova broncodilatadora",
    chapter: "4",
    group: "Pneumologia",
    requiresAuth: false,
  },
  {
    code: "41301032",
    description: "Teste de broncoprovocação",
    chapter: "4",
    group: "Pneumologia",
    requiresAuth: true,
  },
  {
    code: "41301040",
    description: "Pletismografia (volumes pulmonares)",
    chapter: "4",
    group: "Pneumologia",
    requiresAuth: true,
  },
  {
    code: "41301059",
    description: "Difusão de monóxido de carbono (DLCO)",
    chapter: "4",
    group: "Pneumologia",
    requiresAuth: true,
  },
  { code: "41301067", description: "Gasometria arterial", chapter: "4", group: "Pneumologia", requiresAuth: false },
  { code: "41301075", description: "Oximetria noturna", chapter: "4", group: "Pneumologia", requiresAuth: false },
  {
    code: "41301083",
    description: "Teste de caminhada de 6 minutos",
    chapter: "4",
    group: "Pneumologia",
    requiresAuth: false,
  },
  { code: "41301091", description: "Broncoscopia diagnóstica", chapter: "4", group: "Pneumologia", requiresAuth: true },
  { code: "41301105", description: "Lavado broncoalveolar", chapter: "4", group: "Pneumologia", requiresAuth: true },
]

// Compilação completa de todos os procedimentos TUSS
export const ALL_TUSS_PROCEDURES: TUSSProcedure[] = [
  ...CAPITULO_1_PROCEDIMENTOS_GERAIS,
  ...CAPITULO_2_PROCEDIMENTOS_CLINICOS,
  ...CAPITULO_3_CIRURGIAS,
  ...CAPITULO_4_EXAMES,
]

// Total de procedimentos
// export const TOTAL_TUSS_COUNT = ALL_TUSS_PROCEDURES.length // Commenting out to avoid redeclaration

// Função de busca avançada
export function searchTUSS(
  query: string,
  filters?: {
    chapter?: string
    group?: string
    requiresAuth?: boolean
  },
): TUSSProcedure[] {
  const queryLower = query.toLowerCase().trim()

  let results = ALL_TUSS_PROCEDURES

  // Filtrar por capítulo
  if (filters?.chapter) {
    results = results.filter((p) => p.chapter === filters.chapter)
  }

  // Filtrar por grupo
  if (filters?.group) {
    results = results.filter((p) => p.group === filters.group)
  }

  // Filtrar por autorização
  if (filters?.requiresAuth !== undefined) {
    results = results.filter((p) => p.requiresAuth === filters.requiresAuth)
  }

  // Busca textual
  if (queryLower) {
    results = results.filter(
      (p) =>
        p.description.toLowerCase().includes(queryLower) ||
        p.code.includes(queryLower) ||
        p.group.toLowerCase().includes(queryLower),
    )
  }

  return results.slice(0, 50) // Limitar resultados
}

// Obter procedimento por código
export function getTUSSByCode(code: string): TUSSProcedure | undefined {
  return ALL_TUSS_PROCEDURES.find((p) => p.code === code)
}

// Grupos disponíveis
export const TUSS_GROUPS = [
  "Consultas",
  "Visitas",
  "Neonatologia",
  "Acompanhamento",
  "UTI",
  "Pré-natal",
  "Avaliações",
  "Testes",
  "Curativos",
  "Biópsias",
  "Infiltrações",
  "Bloqueios",
  "Dermatologia",
  "Suturas",
  "Imobilizações",
  "Sondagens",
  "Punções",
  "Neurocirurgia",
  "Cirurgia Cardíaca",
  "Cirurgia Torácica",
  "Cirurgia Vascular",
  "Cirurgia Abdominal",
  "Urologia",
  "Ginecologia",
  "Ortopedia",
  "Oftalmologia",
  "Otorrinolaringologia",
  "Hematologia",
  "Bioquímica",
  "Hormônios",
  "Marcadores Tumorais",
  "Urinálise",
  "Fezes",
  "Sorologia",
  "Autoimunidade",
  "Radiologia",
  "Tomografia",
  "Ressonância",
  "Ultrassonografia",
  "Doppler",
  "Mamografia",
  "Densitometria",
  "Cardiologia",
  "Neurologia",
  "Gastroenterologia",
  "Pneumologia",
] as const

// Capítulos TUSS
export const TUSS_CHAPTERS = [
  { code: "1", name: "Procedimentos Gerais" },
  { code: "2", name: "Procedimentos Clínicos" },
  { code: "3", name: "Procedimentos Cirúrgicos e Invasivos" },
  { code: "4", name: "Procedimentos Diagnósticos e Terapêuticos" },
] as const

// Alias for searchTUSS
export const searchTUSSComplete = searchTUSS

// Categories (same as TUSS_GROUPS)
export const TUSS_CATEGORIES = TUSS_GROUPS

// Specialties
export const TUSS_SPECIALTIES = [
  "Clínica Geral",
  "Cardiologia",
  "Dermatologia",
  "Endocrinologia",
  "Gastroenterologia",
  "Geriatria",
  "Ginecologia e Obstetrícia",
  "Hematologia",
  "Infectologia",
  "Mastologia",
  "Nefrologia",
  "Neurologia",
  "Neurocirurgia",
  "Oftalmologia",
  "Oncologia",
  "Ortopedia e Traumatologia",
  "Otorrinolaringologia",
  "Pediatria",
  "Pneumologia",
  "Psiquiatria",
  "Reumatologia",
  "Urologia",
  "Cirurgia Geral",
  "Cirurgia Cardiovascular",
  "Cirurgia Plástica",
  "Cirurgia Torácica",
  "Cirurgia Vascular",
  "Anestesiologia",
  "Medicina do Trabalho",
  "Medicina de Família",
  "Radiologia",
  "Patologia",
  "Medicina Nuclear",
  "Radioterapia",
  "Fisiatria",
  "Acupuntura",
  "Homeopatia",
  "Nutrologia",
] as const

// Total de procedimentos
export const TOTAL_TUSS_PROCEDURES = ALL_TUSS_PROCEDURES.length
